<?php

//descrizioni lunghe costruzioni, flotta, difese, ricerche

$LOCA["it"]["LONG_1"] = "La miniera di metallo fornisce le risorse base per un impero emergente e permette la realizzazione di costruzioni e navi. Il metallo &egrave; la risorsa grezza pi&egrave; economica e richiede poca energia per l estrazione ma viene usato molto pi&ugrave; delle altre risorse. Il metallo si trova molto in profondit&agrave; e ci&ograve; conduce a miniere sempre pi&ugrave; profonde che richiedono sempre pi&ugrave; energia per funzionare.";
$LOCA["it"]["LONG_2"] = "I cristalli sono la principale risorsa utilizzata nei componenti elettronici e sono impiegati anche per formare alcune leghe metalliche. In confronto al processo di produzione del metallo, lavorare cristalli grezzi per ottenere cristalli industriali richiede circa il doppio dell energia; perci&ograve; i cristalli sono molto pi&ugrave; costosi da comprare via commercio. Ogni singola nave e infrastruttura richiede una certa quantit&agrave; di cristalli ma quelli adatti allo scopo sono piuttosto rari e giacciono a grandi profondit&agrave;. Le miniere necessarie per la loro estrazione divengono quindi sempre pi&ugrave; costose, man mano che si sviluppano in profondit&agrave;, ma di certo producono pi&ugrave; cristalli di quelle in superficie.";
$LOCA["it"]["LONG_3"] = "Il deuterio &egrave; utilizzato come carburante per le navi stellari ed &egrave; estratto nelle profondit&agrave; oceaniche. Il deuterio &egrave; una sostanza rara e perci&ograve; relativamente costosa.";
$LOCA["it"]["LONG_4"] = "Per fornire l energia necessaria alle strutture sono richiesti impianti enormi. Una centrale solare &egrave; un modo per creare questa energia. Essa sfrutta i semiconduttori per i pannelli fotovoltaici che convertono i fotoni in corrente elettrica. Pi&ugrave; sar&agrave; alto il livello della centrale solare pi&ugrave; lo sar&agrave; l area dove avviene la conversione e quindi sar&agrave; generata una maggiore quantit&agrave; d energia. Le centrali solari sono la spina dorsale delle infrastrutture planetarie.";
$LOCA["it"]["LONG_12"] = "Una centrale a fusione nucleare produce un atomo di elio partendo da due di deuterio utilizzando pressioni e temperature estremamente alte. Quando due nuclei di deuterio si fondono e creano una particella alpha, c'&egrave; una perdita di massa netta. Questa non scompare ma si trasforma in energia cinetica che pu&ograve; essere convertita in energia elettrica. Ogni grammo di deuterio produce 172MWh di energia perci&ograve; pi&ugrave; &egrave; grande la centrale a fusione, pi&ugrave; fusioni possono avvenire in parallelo aumentando cos&igrave; l' energia complessivamente prodotta.";
$LOCA["it"]["LONG_14"] = "Le fabbriche dei robot forniscono unit&agrave; di costruzione economiche ed affidabili che possono essere usate per costruire o migliorare qualsiasi struttura planetaria. Ogni livello aggiuntivo aumenta l'efficienza e la quantit&agrave; di unit&agrave; robotiche che aiutano la costruzione.";
$LOCA["it"]["LONG_15"] = "I naniti sono delle unit&agrave; robotiche di dimensioni medie pari a qualche nanometro. Questi microbi meccanici sono connessi tra loro e programmati per un lavoro di costruzione; essi offrono una velocit&agrave; di costruzione mai vista prima. I naniti operano a livello molecolare e sono immensamente utili per costruire navi, rimanendo essi parte della struttura della nave; in questo modo essi possono fornire le proprie capacit&agrave; di riparazione ed essere usati per il controllo dei danni e ripararli utilizzando energia e risorse.";
$LOCA["it"]["LONG_21"] = "Il cantiere spaziale &egrave; il luogo dove vengono costruite le navi e le difese planetarie. Man mano che si ingrandisce esso pu&ograve; produrre una sempre maggiore gamma di navi ad un ritmo sempre pi&ugrave; veloce. Se &egrave; presente anche la fabbrica dei naniti sul pianeta, la velocit&agrave; di produzione viene estremamente incrementata.";
$LOCA["it"]["LONG_22"] = "I depositi offrono un enorme spazio per immagazzinare il metallo derivante dalle miniere. Pi&ugrave; sar&agrave; elevata la capacit&agrave; del deposito, pi&ugrave; materiale potr&agrave; contenere. Una volta raggiunta la capacit&agrave; massima non potr&agrave; essere pi&ugrave; estratto metallo dalle miniere.";
$LOCA["it"]["LONG_23"] = "I cristalli estratti dalle miniere sono posti in questi enormi depositi che sono accuratamente controllati, dato il valore dei cristalli. Maggiore sar&agrave; la capacit&agrave; del deposito, pi&ugrave; cristalli potranno essere contenuti. Esaurita la capacit&agrave; non potranno pi&ugrave; essere estratti cristalli dalle miniere.";
$LOCA["it"]["LONG_24"] = "Sono enormi cisterne che contengono il deuterio in eccesso. Queste cisterne sono solitamente vicino al cantiere navale dato che il deuterio &egrave; usato come carburante. Quanto pi&ugrave; elevata &egrave; la capacit&agrave; tanto maggiore sar&agrave; il deuterio che pu&ograve; essere contenuto. Raggiunta la capacit&agrave; massima non si potr&agrave; pi&ugrave; estrarre deuterio.";
$LOCA["it"]["LONG_31"] = "Il laboratorio di ricerca &egrave; indispensabile per l'espansione di un impero in quanto consente di ricercare tecnologie sempre pi&ugrave; avanzate. La crescita del laboratorio di ricerca non porta solo all'abbassamento dei tempi di ricerche ma consente di scoprirne di nuove.";
$LOCA["it"]["LONG_33"] = "La domanda su come rendere disponibile pi&ugrave; spazio per le strutture planetarie cresce di pari passo con l evoluzione delle infrastrutture planetarie in tutta la galassia. I metodi di costruzione tradizionali diventano cos&igrave; insufficienti rispetto all enorme bisogno di spazio.
Un piccolo gruppo di nanotecnologi ha trovato la soluzione: il Terraforming
Usando grandi quantit&agrave; di energia &egrave; possibile effettuare il terraforming su vaste estensioni di territorio, fin quasi alle dimensioni di continenti. Dei naniti specificamente progettati sono costruiti in questa struttura, garantendo la qualit&agrave; e l usabilit&agrave; delle aree terraformate.
<font color=\"red\">Una volta costruito, il terraformer non pu&ograve; essere smantellato.</font>";
$LOCA["it"]["LONG_34"] = "La base d'appoggio offre la possibilit&agrave; di rifornirsi alle flotte amiche in orbita che aiutano a difenderti. Ogni livello aggiunto a questa struttura d&agrave; alle flotte in orbita 10.000 unit&agrave; di deuterio per ora in pi&ugrave; come rifornimento.";
$LOCA["it"]["LONG_41"] = "Dato che la luna non ha atmosfera, bisogna avere un avamposto lunare per generare uno spazio abitabile. La base lunare non fornisce solo l ossigeno necessario ma anche la gravit&agrave; artificiale, il riscaldamento e la protezione. Aumentandone il livello si aumenter&agrave; l area per le infrastrutture; ogni livello fornisce 3 spazi lunari finch&egrave; la luna non sar&agrave; completamente popolata.
Una volta costruita, la base lunare non pu&ograve; essere smantellata.";
$LOCA["it"]["LONG_42"] = "Lo schieramento di sensori ad alta risoluzione viene usato per analizzare uno spettro di frequenze amplissimo. Unit&agrave; processuali parallele sono poi massicciamente predisposte per analizzare i segnali ricevuti e scovare anche la pi&ugrave; flebile anomalia nella frequenza o intensit&agrave; in modo da rilevare flotte o manovre di imperi distanti. Data la complessit&agrave; del sistema ogni scansione richiede una moderata quantit&agrave; di deuterio per fornire l energia necessaria al processo.";
$LOCA["it"]["LONG_43"] = "I portali iperspaziali sono enormi impianti ricetrasmittenti e sono capaci di inviare anche la pi&ugrave; grande flotta istantaneamente ad un altro portale in una qualsiasi galassia. Il portale richiede le tecnologie pi&ugrave; sofisticate come del resto un immensa quantit&agrave; d energia per funzionare.";
$LOCA["it"]["LONG_44"] = "La base missilistica &egrave; una struttura di lancio e di stoccaccio di missili planetari.Hai spazio per 5 missili interplanetari o 10 antimissili per ogni livello della tua base. E' possibile utilizzare gli spazi con combinazioni diverse; 1 missile interplanetario occupa 2 spazi, gli antimissili 1.";

$LOCA["it"]["LONG_106"] = "La tecnologia per lo spionaggio &egrave; la ricerca dei sensori di dati e degli equipaggiamenti di intelligence e delle conoscenze di cui un impero ha bisogno per proteggersi dall attacco di spie nemiche e per inviarne di proprie. Pi&ugrave; &egrave; avanzata la ricerca, maggiori saranno i dettagli che possono essere ottenuti sugli altri imperi.

Per i satelliti spia e la loro possibilit&agrave; di successo, la differenza tra il proprio livello di ricerca in questo campo e quello spiato &egrave; importante. Ad un maggiore sviluppo della ricerca corrispondono informazioni maggiori e pi&ugrave; dettagliate dai satelliti spia, e sar&agrave; inoltre minore la probabilit&agrave; che la sonda sia intercettata dalle forze planetarie spiate. Pi&ugrave; sonde spia saranno inviate, maggiori saranno i dettagli ma anche le possibilit&agrave; di intercettazione.
Il livello della ricerca definisce inoltre il livello di dettagli di una flotta in arrivo:<br><br>
- Il livello 2 aggiunge il numero totale di navi alle informazioni sulla flotta<br>
- Il livello 4 aggiunge ai dati il tipo di navi in avvicinamento<br>
- Il livello 8, per finire, offre dettagli riguardo il numero e il tipo di navi.<br><br>

In generale, le tecnologie per lo spionaggio sono molto importanti per ogni impero che sia aggressivo o amichevole. E consigliabile iniziare le ricerche in quest area dopo aver creato le navi cargo piccole.";
$LOCA["it"]["LONG_108"] = "La tecnologia informatica viene utilizzata per costruire unit&agrave; processuali e di controllo dati sempre pi&ugrave; potenti. Ogni livello aumenta la potenza di calcolo e il livello di parallelismo. Pi&ugrave; questa tecnologia &egrave; sviluppata, maggiori saranno i posti nella flotta. Pi&ugrave; posti ha un impero, maggiore sar&agrave; l attivit&agrave; che genera introiti. I posti nella flotta sono utilizzati per navi militari come per cargo o manovre di spionaggio, &egrave; una buona idea aumentare costantemente la ricerca in quest area per fornire un adeguata flessibilit&agrave; alla flotta.";
$LOCA["it"]["LONG_109"] = "Le tecnologie delle armi cercano di sviluppare ulteriormente le armi disponibili. Esse sono principalmente focalizzate nell aumento della potenza e efficienza dei sistemi d armamento.
In questo modo aumentando il livello di questa tecnologia la stessa arma ha pi&ugrave; potenza di fuoco e fa pi&ugrave; danni - ogni livello aggiunge il 10% rispetto alla potenza base.
Siccome la tecnologia degli armamenti &egrave; importante per stare al passo con i nemici, &egrave; una buona idea aumentare continuamente le conoscenze in questo campo.";
$LOCA["it"]["LONG_110"] = "Tecnologia degli scudi &egrave; utilizzate per generare uno scudo protettivo a particelle attorno alle strutture. Ogni livello migliora la schermatura del 10% rispetto al livello base di una data struttura. I livelli aggiuntivi aumentano la quantit&agrave; di energia che uno scudo pu&ograve; assorbire prima di cedere. Gli scudi non sono solo usati sulle navi, ma anche per cupole protettive planetarie.";
$LOCA["it"]["LONG_111"] = "Leghe altamente sofisticate aiutano ad aumentare la corazzatura di una nave aggiungendo il 10%, rispetto alla struttura base, di forza per livello. Per una data lega risultata efficace, pu&ograve; essere alterata la struttura molecolare per manipolarne il comportamento in situazioni di combattimento e per incorporare le ultime scoperte tecnologiche.";
$LOCA["it"]["LONG_113"] = "La tecnologia energetica ha a che fare con la conoscenza e il raffinamento delle sorgenti di energia, dei problemi di stoccaggio e delle tecnologie che forniscono il componente fondamentale di oggi: l'energia. Pi&ugrave; questa tecnologia &egrave; sviluppata, pi&ugrave; saranno efficienti i tuoi sistemi. Certi livelli di avanzamento sono addirittura richiesti per poter raggiungere altre tecnologie specifiche che si basano sulla conoscenza dell'energia.";
$LOCA["it"]["LONG_114"] = "Incorporando la quarta e la quinta dimensione nelle tecnologie di propulsione si rende disponibile un nuovo sistema di proulsione, molto pi&ugrave; efficiente e che usa meno carburante dei sistemi tradizionali. Inoltre la tecnologia iperspaziale fornisce la base per i viaggi iperspaziali che sono usati dalle navi maggiori (come i portali dimensionali). Ã&#136; una nuova e complicata tecnologia questa che richiede equipaggiamenti di laboratorio e strutture di test dispendiose.";
$LOCA["it"]["LONG_115"] = "I propulsorsi a combustione appartengono alla pi&ugrave; vecchia categoria di motori esistenti e sono basati sulla repulsione. Le particelle sono accelerate e lasciano il motore generando una forza repulsiva che fa muovere la nave nella direzione opposta. L'efficienza di questi motori a combustione &egrave; bassa ma sono anche poco costosi da costruire e hanno dato prova di affidabilit&agrave;. Le loro dimensioni sono piccole e non richiedono un processo troppo dispendioso per il controllo.
Fare ricerca ad alti livelli garantisce motori sempre pi&ugrave; veloci, dato che ogni livello aggiunge il 10% di velocit&agrave; rispetto al livello base.
Siccome questa tecnologia &egrave; tra le pi&ugrave; fondamentali per un impero emergente, bisognerebbe condurre ricerche non appena possibile.";
$LOCA["it"]["LONG_117"] = "Il propulsore a impulso si basa sul principio di repulsione delle particelle. La materia respinta &egrave; in realt&agrave; costituita dalle scorie generate dal reattore a fusione che fornisce l'energia per questo tipo di propulsione. I motori ad impulso sono uno sviluppo dei motori a combustione ed aumentano l' efficienza di questi, diminuendone i consumi in funzione della velocit&agrave; .";
$LOCA["it"]["LONG_118"] = "Attraverso la curvatura dello spazio-tempo nell ambiente circostante l'astronave, lo spazio viene compresso ad un tal grado che grandi distanze possono essere attraversate in un breve periodo di tempo. Pi&ugrave; &egrave; avanzato lo sviluppo del motore, maggiore sar&agrave; la compressione dello spazio, aumentando cos&igrave; la veloct&agrave; del 30% per ogni livello.";
$LOCA["it"]["LONG_120"] = "Il LASER (Light Amplification by Stimulated Emission of Radiation) &egrave; un raggio fotonico monocromatico e coerente con una focalizzazione estremamente precisa. Le unit&agrave; laser hanno un ampia gamma di utilizzo: dalla navigazione giroscopica ai computer ottici o sistemi d'armamento, la tecnologia laser &egrave; fondamentale per ogni impero.";
$LOCA["it"]["LONG_121"] = "La tecnologia delle armi ioniche studia come focalizzare un fascio di ioni accelerati su un bersaglio creando seri danni grazie agli scudi che sono per natura caricati elettricamente. I raggi ionici sono superiori ai laser ma hanno costi di ricerca maggiori. Nonostante siano piuttosto semplici rispetto ad altre tecnologie, i raggi ionici non sono usati spesso.";
$LOCA["it"]["LONG_122"] = "Le armi al plasma sono pi&ugrave; pericolose di ogni altro armamento conosciuto, a causa della natura dannosa del plasma. Esso &egrave; uno dei quattro stati della materia (solido, liquido, gas, plasma) ed &egrave; composto da un un ugual numer di particelle gassose cariche positivamente e negativamente. Il plasma pu&ograve; essere prodotto da un gas se si utilizza abbastanza energia da causare la ionizzazione dello stesso in nuclei carichi positivamente ed elettroni. Queste particelle cariche vengono compattate in \"scariche\" usando tecniche magnetiche e rendendo possibile sparare le scariche.";
$LOCA["it"]["LONG_123"] = "Gli scienziati dei tuoi pianeti possono comunicare tra loro attraverso questa rete.
Per ogni livello di ricerca il tuo laboratorio con livello pi&ugrave; alto che non sia gi&agrave; collegato al network, verr&agrave; aggiunto alla rete. Quando la rete sar&agrave; stabilita, i loro livelli si sommeranno.
Ogni laboratorio collegato deve avere il livello necessario per la tecnologia che si ha in programma di ricercare. In tal modo si unir&agrave; alla rete.";
$LOCA["it"]["LONG_124"] = "La Tecnologia di Spedizione include notevoli sensori di ricerca e permette l'equipaggiamento di differenti navi con moduli di ricerca. Questi includono un database e un completo laboratorio mobile. Per assicurare la sicurezza della nave durante pericolose ricerche, il modulo di ricerca ha un suo generatore di energia e un generatore di scudi che crea un potente campo di forza in caso di emergenza.";
$LOCA["it"]["LONG_199"] = "Un gravitone &egrave; una particella elementare responsabile degli effetti della gravit&agrave;. Essa non ha massa a riposo, non &egrave; carica e ha spin pari a due. Sparando delle particelle gravitoniche concentrate si crea un campo gravitazionale artificiale la cui potenza e forza attrattiva possono non solo distruggere navi ma addirittura lune intere. Per poter produrre la quantit&agrave; necessaria di gravitoni il pianedta deve poter generare un immensa quantit&agrave; di energia.";

$LOCA["it"]["LONG_202"] = "I cargo leggeri sono grandi, approssimativamente, come i caccia ma hanno motori ed armamenti meno efficienti in modo da ricavare pi&ugrave; spazio per il cargo. Il cargo leggero pu&ograve; contenere 5000 risorse. Data la limitata potenza di fuoco sono sovente accompagnate da altre navi nelle loro missioni.
La velocit&agrave; base dei cargo leggeri &egrave; aumentata non appena viene ricercato il motore a impulso di livello 5 in quanto esse vengono equipaggiati con il nuovo motore.";
$LOCA["it"]["LONG_203"] = "Questo tipo di nave non dovrebbe mai fare missioni da sola perch&egrave; non ha armamenti utili o altre tecnologie, in modo da fornire il massimo spazio per il trasporto. I cargo pesanti possono velocemente rifornire pianeti grazie anche ai suoi motori a combustione altamente sofisticati. Naturalmente esso accompagna la flotta sui pianeti attaccati per recuperare tante pi&ugrave; risorse possibili.";
$LOCA["it"]["LONG_204"] = "Data la loro corazza leggera e il semplice sistema d'armamento, i caccia leggeri appartengono alle navi di supporto in battaglia. La loro agilit&agrave; e velocit&agrave; insieme alla quantit&agrave; di navi che attaccano, pu&ograve; farle apparire come un diversivo rispetto alle navi pi&ugrave; grandi che non sono cos&igrave; manovrabili.";
$LOCA["it"]["LONG_205"] = "Durante lo sviluppo del caccia leggero i ricercatori sono arrivati al punto in cui la guida convenzionale raggiunse i propri limiti. Per fornire l agilit&agrave; necessaria ai nuovi caccia, &egrave; stato usato per la prima volta un motore ad impulso. Nonostante i costi aggiuntivi e la complessit&agrave; si sono rivelate nuove possibilit&agrave; in parte grazie al maggior costo dei materiali generalmente utilizzati. Tramite l uso della tecnologia d impulso, &egrave; stata resa disponibile pi&ugrave; energia per le armi e gli scudi. La corazzatura migliorata e un maggior numero di armi rendono questo caccia una minaccia maggiore rispetto ai suoi predecessori.";
$LOCA["it"]["LONG_206"] = "Con la comparsa di laser pesanti e cannoni a ioni sui campi di battaglia, le navi da combattimento vennero sempre pi&ugrave; sopraffatte. Nonostante le molte modifiche la potenza di fuoco e la corrazzatura dello scafo non poterono essere migliorati a sufficienza per affrontare questi nuovi sistemi di difesa.
Questo &egrave; il motivo per il quale &egrave; stato scelto di sviluppare un tipo di nave completamente nuovo, fornendo pi&ugrave; corazzatura e armi pi&ugrave; potenti. Cos&igrave; nacque l incrociatore da battaglia. Gli incrociatori hanno una corazza almeno tre volte pi&ugrave; potente dei caccia pesanti e hanno a disposizione pi&ugrave; del doppio di potenza d fuoco. La loro velocit&agrave; di crociera &egrave; allo stesso modo superiore ad ogni altra cosa vista prima. Non c &egrave; praticamente nessuna nave migliore contro le difese planetarie leggere o medie e perci&ograve; gli incrociatori sono stati ampiamente adottati in tutto l universo da almeno un centinaio di anni.
Sfortunatamente con la creazione dei nuovi e potenti sistemi difensivi come il cannone di Gauss o gli emettitori di plasma, il regno degli incrociatori fin&igrave; presto. Al giorno d oggi essi vengono ancora usati per combattere contro battaglioni di caccia dato l efficace sistema d armamento contro questi ultimi.";
$LOCA["it"]["LONG_207"] = "Le navi da battaglia sono la spina dorsale di ogni flotta militare. La loro corazzatura rinforzata, abbinata a degli armamenti pesanti, e una velocit&agrave; di crociera elevata, rende questa nave indispensabile per ogni impero. Inoltre possiede un ampia stiva che &egrave; ottima in situazioni ostili.";
$LOCA["it"]["LONG_208"] = "La colonizzatrice &egrave; una nave dal compito specifico, ben corazzata, e permette ad un impero di espandersi e stabilirsi su nuovi mondi. La struttura della nave &egrave; abilmente utilizzata per ospitare le risorse necessarie a costruire le prime strutture planetarie. Un impero pu&ograve; avere fino a 8 colonie oltre al pianeta principale.";
$LOCA["it"]["LONG_209"] = "I combattimenti nello spazio sembrano diventare sempre pi&ugrave; grandi e in una singola battaglia migliaia di navi possono essere distrutte, con il rischio di perdere per sempre i detriti che vanno alla deriva. Le navi cargo standard non hanno il compito di raccogliere risorse importanti o anche semplicemente avvicinarsi ad esse.
Con il nuovo sviluppo di navi stellari riciclatrici speciali, e basandosi sulla conoscenza in crescita riguardo alle tecnologie di schermatura, alla fine &egrave; diventato possibile raccogliere quei campi di importanti detriti. Le navi riciclatrici sono simili in dimensione alle navi cargo grandi, nonostante questo le installazioni addizionali tecniche necessarie per il compito richiedono maggiore spazio. E per questo che le navi riciclatrici hanno una capacit&agrave; di deposito limitata a 20.000.";
$LOCA["it"]["LONG_210"] = "Le sonde spia sono piccoli droni non pilotati dall uomo con sistemi di propulsione eccezionalmente veloci usati per spiare mondi stranieri. Con i loro sistemi di comunicazione altamente avanzati queste sonde posso inviare da grandi distanze informazioni di spionaggio.
Una volta arrivate nell orbita del pianeta bersaglio, le sonde rimangono la in modo da poter raccogliere informazioni e durante quel periodo sono relativamente facili da rilevare. A causa dei limiti di dimensione e peso, non sono state incorporate strutture di copertura o scudi cos&igrave; come i droni non hanno alcun sistema d armamento. Una volta rilevate, le sonde normalmente vengono distrutte a causa della loro debole struttura.";
$LOCA["it"]["LONG_211"] = "Il bombardiere &egrave; una nave stellare speciale sviluppata per sfondare pesanti difese planetarie. Grazie ad un sistema di puntamento con guida laser, possono essere sganciate bombe al plasma con precisione sul bersaglio, causando enorme distruzione tra i sistemi di difesa planetari.
La velocit&agrave; base dei bombardieri &egrave; aumentata non appena viene ricercato il motore iperspaziale di livello 8 in quanto essi vengono equipaggiati con il nuovo motore.";
$LOCA["it"]["LONG_212"] = "I satelliti solari sono semplici satelliti in orbita equipaggiati di celle fotovoltaiche e servono a trasferire energia al pianeta. L'energia in questo modo &egrave; trasmessa a terra utilizzando un raggio laser speciale. L'efficienza di queste piattaforme &egrave; legata all'ammontare di luce solare, rendendole pi&ugrave; o meno efficaci a seconda della distanza dei pianeti dal sole attorno al quale orbitano.
A causa del loro basso costo e della facilit&agrave; di installazione, questi satelliti sono vastamente conosciuti per l'aiuto che danno all'approvvigionamento energetico delle infrastrutture di un pianeta.
Sfortunatamente, durante gli attacchi, questi satelliti vengono distrutti in gran numero.";
$LOCA["it"]["LONG_213"] = "Con la corazzata, la madre di tutte le navi da guerra entra nell arena. Il suo sistema multi-falange di armamento consiste di cannoni ionici, al plasma e di Gauss montati su torrette veloci nella risposta che permettono loro di eliminare i caccia operativi con un margine di successo del 99%. La dimensione della nave &egrave; d'altro canto il suo svantaggio dal momento che la manovrabilit&agrave; &egrave; limitata, facendo della corazzata pi&ugrave; una stazione da combattimento che una nave da guerra. Il consumo di carburante di queste immense corazzate &egrave; per&ograve; tanto alto quanto lo &egrave; il loro potere di fuoco...";
$LOCA["it"]["LONG_214"] = "La morte nera &egrave; equipaggiata con un singolo gigantesco Cannone di Gauss in grado di distruggere praticamente qualsiasi cosa con un singolo colpo, sia che siano corazzate o lune. In modo da produrre l'energia necessaria per quest arma, enormi parti all'interno della Morte Nera sono utilizzate come generatori di potenza. La dimensione della Morte Nera inoltre ne limita la velocit&agrave; negli spostamenti, che &egrave; molto bassa. Si dice che spesso il capitano aiuti a spingerla per aumentarne la velocit&agrave;.
Solo imperi immensi e avanzati hanno la manodopera e le conoscenze estese richieste per poter costruire una tale nave stellare della dimensione di una luna.";
$LOCA["it"]["LONG_215"] = "Questa nave, &egrave; una grande invenzione tecnologica,  pu&ograve; essere veramente pericolosa qualora arrivi per distruggere le flotte attaccanti. Con i relativi cannoni laser migliorati pu&ograve; essere classificata fra le navi pi&ugrave; grandi che esistano, dal momento che &egrave; progettata per sconfiggerle. A causa del suo design piccolo ed i suoi enormi armamenti, la stiva &egrave; ridotta al minimo ma questo svantaggio &egrave; compensato dal basso consumo di carburante del propulsore iperspaziale.";

$LOCA["it"]["LONG_401"] = "Il lanciamissili &egrave; un semplice ma indispensabile sistema di difesa. Diventa abbastanza funzionale se in grandi quantit&agrave; e pu&ograve; essere costruito senza specifiche ricerche perch&egrave; &egrave; una semplice arma balistica. Il basso costo di produzione lo rende adeguato contro piccole flotte, ma diventa sempre meno efficace con l incremento dei sistemi di difesa. In successivi sviluppi risulta essere utilizzato solo come specchietto per le allodole nei combattimenti.";
$LOCA["it"]["LONG_402"] = "Per tenere il passo con la velocit&agrave; di sviluppo sempre in aumento in termini di tecnologie aerospaziali, gli scienziati dovettero sviluppare un nuovo tipo di sistema di difesa in grado di gestire navi e flotte sempre pi&ugrave; forti e meglio equipaggiate.
In breve nacque l unit&agrave; laser piccola, che era in grado di sparare sul bersaglio un raggio laser altamente concentrato e causare molto pi&ugrave; danno dell impatto di missili balistici. Dall altro lato, fu migliorata la schermatura dei cannoni per gestire le maggiori potenze di fuoco delle moderne navi. Dal momento che il basso costo dell unit&agrave; era un obiettivo essenziale designato, la struttura di base non &egrave; migliorata rispetto al lancia-missili.
Poich&egrave; il laser leggero offre un vantaggioso rapporto qualit&agrave;-prezzo, &egrave; il pi&ugrave; conosciuto sistema di difesa essendo usato contemporaneamente da piccoli imperi in crescita e da grandi imperi multigalattici.";
$LOCA["it"]["LONG_403"] = "Il laser pesante &egrave; la diretta evoluzione del sistema laser piccolo, ha infatti una migliorata integrit&agrave; strutturale e vi sono adottati nuovi materiali. In questo modo &egrave; stato possibile migliorare la struttura di copertura e grazie all installazione di nuovi sistemi computerizzati ed energetici, molta pi&ugrave; energia, rispetto a quando si usavano le unit&agrave; laser piccole, &egrave; rilasciata contro il bersaglio.";
$LOCA["it"]["LONG_404"] = "Le armi a proiettili erano considerate obsolete date la moderna tecnologia di fusione nucleare, le nuove fonti di energia, la scoperta della tecnologia iperspaziale e la ulteriormente migliorata tecnologia delle leghe. Per&ograve; &egrave; la stessa tecnologia energetica che una volta ne prese il posto, che ora le richiama indietro in modo da potersi muovere verso il nuovo secolo: il principio di base &egrave; da lungo conosciuto e si data a cavallo del 20esimo e 21esimo secolo: l acceleratore di particelle.
Un cannone di Gauss in realt&agrave; non &egrave; altro che un acceleratore di particelle di enorme misura dove i proiettili di parecchie tonnellate di peso vengono accelerati utilizzando immense spirali elettromagnetiche. La velocit&agrave; di uscita di questi grandi proiettili &egrave; cos%igrave; elevata da bruciare la polvere nell aria circostante e il rinculo del colpo scuote il terreno.
Anche le tecnologie di schermatura e di leghe protettive pi&ugrave; innovate con difficolt&agrave; resistono all impatto di tali proiettili - capita la maggior parte delle volte, che il proiettile semplicemente passi attraverso la struttura bersaglio.";
$LOCA["it"]["LONG_405"] = "Nel 21esimo secolo esisteva una tecnologia chiamata EMP, che sta per impulso elettromagnetico. Un tale impulso energetico si dimostra principalmente pericoloso per i sistemi che utilizzano elettricit&agrave; o sono sensibili ad essa. In quei tempi, tali armi erano trasportate in bombe o razzi missilistici, ma con il continuo sviluppo nell area degli EMP, &egrave; oggi possibile montare tali unit&agrave; in semplici cannoni. Il cannone ionico &egrave; fino a questo punto il miglior equipaggiamento per queste armi. Il raggio ionico mirato distrugge sul bersaglio ogni sistema elettrico non schermato e destabilizza il sistema di scudi della nave stellare. In combinazione questo spesso significa la distruzione totale nonostante il fatto che gli esseri viventinon vengano colpiti direttamente.
L unica nave che si sappia usi i cannoni ionici &egrave; l incrociatore da battaglia, a causa delle alte richieste di energia da parte di questi cannoni e il fatto che il combattimento spesso richieda la distruzione del bersaglio non il paralizzarlo.";
$LOCA["it"]["LONG_406"] = "La tecnologia laser &egrave; stata portata quasi alla perfezione, la tecnologia ionica sembrava aver raggiunto il massimo e in generale non vi era visione di come sarebbe stato possibile ottenere un miglioramento degli esistenti sistemi d armamento. Ma questo cambier&agrave; una volta che sar&agrave; nata l idea di mettere assieme le due tecnologie. Mentre il laser &egrave; utilizzato per scaldare le particelle di deuterio a milioni di gradi, la tecnologia ionica carica elettricamente queste particelle e le conoscenze in elettromagnetismo permettono di contenere questo pericoloso plasma.
La scarica blu del plasma &egrave; molto bella quando &egrave; in movimento verso il suo obiettivo, ma dal punto di vista dell equipaggio di una nave stellare, questa sfera di plasma apparentemente amichevole significa morte e distruzione. Gli armamenti al plasma sono identificati come le pi&ugrave; pericolose minacce, ma hanno il loro costo.";
$LOCA["it"]["LONG_407"] = "Molto prima che i generatori di scudi diventassero integrati e portatili, c'erano vecchi grandi generatori sulla superficie dei pianeti. Quelli erano in grado di disporre una enorme cupola difensiva attorno alla superficie dell intero pianeta capace di assorbire grandi quantit&agrave; di energia qualora subisse un attacco. Ogni tanto capita che un piccolo convoglio da combattimento venga abbattuto da queste cupole-scudo. Usando tecnologie di schermatura sempre pi&ugrave; avanzate, queste cupole possono essere migliorate ulteriormente, cos&igrave;­ che la loro abilit&agrave; di assorbire energia sia ancora pi&ugrave; grande.
Chiaramente solo una di ciascuna cupola-scudo pu&ograve; essere costruita su un pianeta.";
$LOCA["it"]["LONG_408"] = "Questa &egrave; una versione avanzata della cupola scudo e la sua principale carattestica &egrave; la maggiore capacit&agrave; di assorbimento d energia. Si basa sulla stessa conoscenza tecnologica delle cupole pi&ugrave; piccole. I generatori sono inoltre meno rumorosi quando in azione.";

$LOCA["it"]["LONG_502"] = "I missili anti-missili distruggono i missili attaccanti. Ogni missile anti-missile distrugge un missile interplanetario.";
$LOCA["it"]["LONG_503"] = "I missili interplanetari distruggono le difese nemiche. Le difese distrutte dai missili interplanetari non verranno ricostruite.";

?>