<?php

// Expanded description of objects.

$LOCA["es"]["LONG_1"] = "El metal es el recurso principal utilizado en la fundación de tu imperio. A mayores profundidades, las minas pueden producir más cantidad de metal utilizable para la construcción de edificios, naves, sistemas de defensa e investigación. Cuanto más profundo perforan las minas, más energía se requiere para alcanzar la producción máxima. Como el metal es el más abundante de todos los recursos disponibles, se considera que su valor es el más bajo de todos los recursos para el comercio.";
$LOCA["es"]["LONG_2"] = "Las minas de cristal suministran el recurso principal utilizado para producir circuitos electrónicos y ciertos compuestos de aleación. La extracción de cristal consume aproximadamente una vez y media más energía que la extracción de metal, lo que hace que el cristal sea más valioso. Casi todas las naves y todos los edificios requieren cristal. Sin embargo, la mayoría de los cristales necesarios para construir naves espaciales son muy raros y, al igual que el metal, solo se encuentran a cierta profundidad. Por lo tanto, construir minas en estratos más profundos aumentará la cantidad de cristal producido.";
$LOCA["es"]["LONG_3"] = "El deuterio también se denomina hidrógeno pesado. Es un isótopo estable del hidrógeno con una abundancia natural en los océanos de las colonias de aproximadamente un átomo por cada 6500 de hidrógeno (~154 PPM). El deuterio representa por tanto aproximadamente el 0,015% (en peso, el 0,030%) del total. El deuterio se procesa mediante sintetizadores especiales que pueden separar el agua del deuterio usando centrifugadoras diseñadas especialmente. La mejora del sintetizador permite aumentar la cantidad de depósitos de deuterio procesados. El deuterio se utiliza para realizar escaneos con la phalanx de sensores, ver galaxias, como combustible para las naves y para llevar a cabo mejoras de investigación especializadas.";
$LOCA["es"]["LONG_4"] = "Se utilizan gigantescos paneles solares para generar energía para las minas y el sintetizador de deuterio. A medida que se mejora la planta de energía solar, aumenta la superficie de células fotovoltaicas que cubren el planeta, lo que resulta en una mayor producción de energía en las redes eléctricas de tu planeta.";
$LOCA["es"]["LONG_12"] = "En las plantas de energía de fusión, los núcleos de hidrógeno se fusionan en núcleos de helio bajo una temperatura y presión enormes, liberando cantidades enormes de energía. Por cada gramo de deuterio consumido se pueden producir hasta 41,32*10^-13 julios de energía; con 1 g se pueden producir 172 MWh de energía.<br/>
Los complejos de reactores más grandes utilizan más deuterio y pueden producir más energía por hora. El rendimiento energético puede aumentarse investigando la tecnología de energía.<br/>
La producción de energía de la planta de fusión se calcula así:<br/>
30 * [Nivel de la planta de fusión] * (1,05 + [Nivel de tecnología de energía] * 0,01) ^ [Nivel de la planta de fusión]";
$LOCA["es"]["LONG_14"] = "El objetivo principal de la fábrica de robots es la producción de robots de construcción de última generación. Cada mejora de la fábrica de robots da como resultado la producción de robots más rápidos, que se utilizan para reducir el tiempo necesario para construir edificios.";
$LOCA["es"]["LONG_15"] = "Una nanomáquina, también llamada nanita, es un dispositivo mecánico o electromecánico cuyas dimensiones se miden en nanómetros (millonésimas de milímetro, o unidades de 10^-9 metros). El tamaño microscópico de las nanomáquinas se traduce en una mayor velocidad de operación. Esta fábrica produce nanomáquinas que son la evolución definitiva de la tecnología robótica. Una vez construida, cada mejora disminuye significativamente el tiempo de producción de edificios, naves y estructuras de defensa.";
$LOCA["es"]["LONG_21"] = "El astillero planetario es responsable de la construcción de naves espaciales y mecanismos de defensa. A medida que se mejora el astillero, puede producir una mayor variedad de vehículos a mucha mayor velocidad. Si hay una fábrica de nanitas en el planeta, la velocidad a la que se construyen las naves aumenta enormemente.";
$LOCA["es"]["LONG_22"] = "Esta gigantesca instalación de almacenamiento se utiliza para almacenar mineral de metal. Cada nivel de mejora aumenta la cantidad de mineral de metal que se puede almacenar. Si los almacenes están llenos, no se extraerá más metal.";
$LOCA["es"]["LONG_23"] = "El cristal sin procesar se almacenará mientras tanto en estas gigantescas naves de almacenamiento. Con cada nivel de mejora, aumenta la cantidad de cristal que se puede almacenar. Si los almacenes de cristal están llenos, no se extraerá más cristal.";
$LOCA["es"]["LONG_24"] = "El tanque de deuterio sirve para almacenar el deuterio recién sintetizado. Una vez procesado por el sintetizador, se canaliza a este tanque para su uso posterior. Con cada mejora del tanque, aumenta la capacidad total de almacenamiento. Una vez alcanzada la capacidad, no se sintetizará más deuterio.";
$LOCA["es"]["LONG_31"] = "Como parte esencial de cualquier imperio, los laboratorios de investigación son donde se descubren nuevas tecnologías y se mejoran las antiguas. Con cada nivel construido del laboratorio de investigación, aumenta la velocidad con la que se investigan nuevas tecnologías, a la vez que se desbloquean tecnologías más nuevas para investigar. Para llevar a cabo la investigación lo más rápido posible, los científicos investigadores son enviados de inmediato a la colonia para comenzar el trabajo y el desarrollo. De esta manera, el conocimiento sobre nuevas tecnologías puede difundirse fácilmente por todo el imperio.";
$LOCA["es"]["LONG_33"] = "Con el aumento de la construcción en los planetas, incluso el espacio habitable de la colonia es cada vez más limitado. Los métodos tradicionales, como la construcción en altura y la construcción subterránea, resultan cada vez más insuficientes. Un pequeño grupo de físicos de alta energía e ingenieros de nanotecnología llegó finalmente a la solución: la terraformación.<br/>
Haciendo uso de cantidades enormes de energía, el terraformador puede hacer cultivables extensiones enteras de tierra o incluso continentes. Este edificio alberga la producción de nanitas creadas específicamente para este propósito, que garantizan una calidad del terreno uniforme en toda la superficie.";
$LOCA["es"]["LONG_34"] = "El depósito de la alianza suministra combustible a las flotas amigas en órbita que colaboran en la defensa. Por cada nivel de mejora del depósito de la alianza, se puede enviar una cantidad especial de deuterio por hora a una flota en órbita.";
$LOCA["es"]["LONG_41"] = "Una luna no tiene atmósfera, por lo que primero debe construirse una base lunar antes de poder establecer un asentamiento. Esta proporciona entonces oxígeno, calefacción y gravedad. Con cada nivel construido, se proporciona un área de vivienda y desarrollo mayor dentro de la biosfera. Cada nivel construido permite tres campos para otros edificios. Con cada nivel, la base lunar ocupa ella misma un campo.<br/>
Una vez construida, la base lunar no puede ser demolida.";
$LOCA["es"]["LONG_42"] = "Utilizando sensores de alta resolución, la phalanx de sensores escanea primero el espectro de luz, la composición de gases y las emisiones de radiación de un mundo lejano y transmite los datos a un superordenador para su procesamiento. Una vez obtenida la información, el superordenador compara los cambios en el espectro, la composición de gases y las emisiones de radiación con un gráfico base de los cambios conocidos del espectro creados por los distintos movimientos de las naves. Los datos resultantes muestran entonces la actividad de cualquier flota dentro del alcance de la phalanx. Para evitar que el superordenador se sobrecaliente durante el proceso, se enfría utilizando 5k de deuterio procesado.<br/>
Para usar la phalanx, haz clic en cualquier planeta de la vista de galaxia dentro del alcance de tus sensores.";
$LOCA["es"]["LONG_43"] = "Una puerta de salto es un sistema de enormes transmisores capaz de enviar incluso las flotas más grandes a una puerta receptora en cualquier lugar del universo sin pérdida de tiempo. Utilizando una tecnología similar a la de un agujero de gusano para realizar el salto, no se requiere deuterio. Debe transcurrir un período de recarga de unos minutos entre saltos para permitir la regeneración. Tampoco es posible transportar recursos a través de la puerta. Con cada nivel de mejora, el tiempo de recarga de la puerta de salto puede reducirse.";
$LOCA["es"]["LONG_44"] = "Los silos de misiles se utilizan para construir, almacenar y lanzar misiles interplanetarios y antibalísticos. Con cada nivel del silo, se pueden almacenar cinco misiles interplanetarios o diez misiles antibalísticos. Un misil interplanetario ocupa el mismo espacio que dos misiles antibalísticos. Está permitido almacenar misiles interplanetarios y antibalísticos en el mismo silo.";

$LOCA["es"]["LONG_106"] = "La tecnología de espionaje es, en primer lugar, un avance de la tecnología de sensores. Cuanto más avanzada esté esta tecnología, más información recibirá el usuario sobre las actividades en su entorno.
La diferencia entre tu propio nivel de espionaje y los niveles de espionaje de los oponentes es crucial para las sondas. Cuanto más avanzada esté tu propia tecnología de espionaje, más información podrá recopilar el informe y menor será la probabilidad de que tus actividades de espionaje sean descubiertas. Cuantas más sondas envíes en una misión, más detalles podrán recopilar del planeta objetivo. Pero al mismo tiempo también aumenta la probabilidad de ser descubierto.
La tecnología de espionaje también mejora la probabilidad de localizar flotas extranjeras. El nivel de espionaje es vital para determinarlo. A partir del nivel 2, se muestra el número total exacto de naves atacantes junto con la notificación normal de ataque. Y a partir del nivel 4, se muestra el tipo de naves atacantes además del número total, y a partir del nivel 8 se muestra el número exacto de los distintos tipos de naves.
Esta tecnología es indispensable para un ataque inminente, ya que te informa de si la flota víctima tiene defensas disponibles o no. Por eso esta tecnología debería investigarse muy pronto.";
$LOCA["es"]["LONG_108"] = "Una vez lanzadas en cualquier misión, las flotas son controladas principalmente por una serie de ordenadores ubicados en el planeta de origen. Estos enormes ordenadores calculan el tiempo exacto de llegada, controlan las correcciones de rumbo según sea necesario, calculan trayectorias y regulan las velocidades de vuelo.<br/>
Con cada nivel investigado, el ordenador de vuelo se mejora para permitir lanzar una ranura adicional. La tecnología de computación debería desarrollarse continuamente durante la construcción de tu imperio.";
$LOCA["es"]["LONG_109"] = "La tecnología de armas es una tecnología de investigación clave y es fundamental para tu supervivencia frente a los imperios enemigos. Con cada nivel investigado de tecnología de armas, los sistemas de armamento de las naves y tus mecanismos de defensa se vuelven cada vez más eficientes. Cada nivel aumenta la fuerza base de tus armas en un 10% del valor base.";
$LOCA["es"]["LONG_110"] = "Con la invención del generador de magnetosfera, los científicos aprendieron que se podía producir un escudo artificial para proteger a la tripulación de las naves espaciales no solo del duro entorno de radiación solar del espacio profundo, sino también de los disparos enemigos durante un ataque. Una vez que los científicos perfeccionaron finalmente la tecnología, se instaló un generador de magnetosfera en todas las naves y sistemas de defensa.<br/>
A medida que la tecnología avanza a cada nivel, el generador de magnetosfera se mejora, lo que proporciona un 10% adicional de fuerza al valor base de los escudos.";
$LOCA["es"]["LONG_111"] = "El entorno del espacio profundo es duro. Los pilotos y las tripulaciones de diversas misiones no solo se enfrentaban a la intensa radiación solar, sino también a la posibilidad de ser alcanzados por desechos espaciales o destruidos por el fuego enemigo durante un ataque. Con el descubrimiento de una aleación de carburo de titanio, litio y aluminio, que resultó ser ligera y duradera a la vez, la tripulación obtuvo cierto grado de protección. Con cada nivel de tecnología de blindaje desarrollado, se produce una aleación de mayor calidad, que aumenta la fuerza del blindaje en un 10%.";
$LOCA["es"]["LONG_113"] = "A medida que avanzaban diversos campos de investigación, se descubrió que la tecnología actual de distribución de energía no era suficiente para iniciar ciertas investigaciones especializadas. Con cada mejora de tu tecnología de energía, se puede llevar a cabo nueva investigación que desbloquea el desarrollo de naves y defensas más sofisticadas.";
$LOCA["es"]["LONG_114"] = "En teoría, la idea del viaje por hiperespacio se basa en la existencia de una dimensión separada y adyacente. Cuando se activa, un motor de hiperespacio introduce la nave estelar en esa otra dimensión, donde puede recorrer vastas distancias en una cantidad de tiempo muy inferior a la que tardaría en el espacio \"normal\". Una vez alcanza el punto del hiperespacio que corresponde a su destino en el espacio real, reaparece.";
$LOCA["es"]["LONG_115"] = "El motor de combustión es la más antigua de las tecnologías, pero sigue en uso. Con el motor de combustión, el escape se forma a partir de los propelentes transportados dentro de la nave antes de su uso. En una cámara cerrada, las presiones son iguales en todas las direcciones y no se produce aceleración. Si se proporciona una abertura en la parte inferior de la cámara, la presión ya no se opone en ese lado. La presión restante produce un empuje resultante en el lado opuesto a la abertura, que impulsa la nave hacia adelante expulsando el escape hacia atrás a velocidad extremadamente alta.<br/>
Con cada nivel desarrollado del motor de combustión, la velocidad de los cargueros pequeños y grandes, los cazadores ligeros, los recicladores y las sondas de espionaje aumenta en un 10%.";
$LOCA["es"]["LONG_117"] = "El motor de impulso se basa en el principio de retroceso, por el cual la emisión estimulada de radiación se produce principalmente como producto de desecho de la fusión nuclear central para obtener energía. Además, se pueden inyectar otras masas. Con cada nivel desarrollado del motor de impulso, la velocidad de los bombarderos, cruceros, cazadores pesados y naves de colonización aumenta en un 20% del valor base. Además, los transportadores pequeños se equipan con motores de impulso en cuanto su nivel de investigación alcanza el 5. En cuanto la investigación del motor de impulso alcanza el nivel 17, los recicladores se reequipan con motores de impulso.<br/>
Los misiles interplanetarios también viajan más lejos con cada nivel.";
$LOCA["es"]["LONG_118"] = "En las inmediaciones de la nave, el espacio se deforma para poder recorrer largas distancias muy rápidamente. Cuanto más desarrollado esté el motor de hiperespacio, más fuerte será la deformación del espacio, por lo que la velocidad de las naves equipadas con él (cruceros de batalla, acorazados, destructores, estrellas de la muerte, exploradores y segadoras) aumenta en un 30% por nivel. Además, el bombardero se construye con un motor de hiperespacio en cuanto la investigación alcanza el nivel 8. En cuanto la investigación del motor de hiperespacio alcanza el nivel 15, el reciclador se reequipa con un motor de hiperespacio.";
$LOCA["es"]["LONG_120"] = "Los láseres (amplificación de luz por emisión estimulada de radiación) producen una emisión intensa y rica en energía de luz coherente. Estos dispositivos pueden utilizarse en todo tipo de ámbitos, desde ordenadores ópticos hasta armas láser pesadas, que atraviesan sin esfuerzo la tecnología de blindaje. La tecnología láser proporciona una base importante para la investigación de otras tecnologías de armas.";
$LOCA["es"]["LONG_121"] = "Los iones pueden concentrarse y acelerarse hasta formar un haz letal. Estos haces pueden entonces infligir un daño enorme. Nuestros científicos también han desarrollado una técnica que reducirá claramente los costes de demolición de edificios y sistemas.";
$LOCA["es"]["LONG_122"] = "Un desarrollo posterior de la tecnología iónica que no acelera iones, sino plasma de alta energía, que puede infligir un daño devastador al impactar contra un objeto. Nuestros científicos también han encontrado una forma de mejorar notablemente la extracción de metal y cristal con esta tecnología.";
$LOCA["es"]["LONG_123"] = "Esta es tu red de espacio profundo para comunicar los resultados de la investigación a tus colonias. Con la IRN, se pueden lograr tiempos de investigación más rápidos vinculando los laboratorios de investigación del nivel más alto, igual al nivel de la IRN desarrollada.<br/>
Para que funcione, cada colonia debe poder llevar a cabo la investigación de forma independiente.";
$LOCA["es"]["LONG_124"] = "La tecnología de expedición abarca diversas tecnologías de escaneo y permite equipar naves de distintas clases con un módulo de investigación. Contiene una base de datos, un pequeño laboratorio móvil, así como varias biocélulas y recipientes de muestras.  Para la seguridad de la nave al explorar objetos peligrosos, el módulo de investigación está equipado con un suministro de energía autónomo y un generador de campos de energía, que puede rodear el módulo de investigación con un potente campo de energía en situaciones extremas.";
$LOCA["es"]["LONG_199"] = "Un gravitón es una partícula elemental sin masa y sin carga. Determina la fuerza gravitatoria. Disparando una carga concentrada de gravitones, se puede construir un campo gravitatorio artificial. No muy distinto de un agujero negro, atrae la masa hacia sí mismo. Así puede destruir naves e incluso lunas enteras. Para producir una cantidad suficiente de gravitones, se requieren enormes cantidades de energía. La investigación de gravitones es necesaria para construir una destructiva estrella de la muerte.";

$LOCA["es"]["LONG_202"] = "Los transportadores tienen aproximadamente el mismo tamaño que los cazadores, pero renuncian a los motores de alto rendimiento y al armamento de a bordo para ganar capacidad de carga. Como resultado, un transportador solo debería enviarse a la batalla cuando vaya acompañado de naves listas para el combate.<br/>
En cuanto el motor de impulso alcanza el nivel de investigación 5, el transportador pequeño viaja con una velocidad base aumentada y está equipado con un motor de impulso.";
$LOCA["es"]["LONG_203"] = "Con el paso del tiempo, los asaltos a las colonias resultaron en la captura de cantidades cada vez mayores de recursos. Como resultado, los cargueros pequeños se enviaban en gran número para compensar las capturas más grandes. Rápidamente se aprendió que se necesitaba una nueva clase de nave para maximizar los recursos capturados en los asaltos, pero que además fuera
rentable. Después de mucho desarrollo, nació el gran carguero.<br/>
Para maximizar los recursos que se pueden almacenar en las bodegas, esta nave tiene poco en cuanto a armas o blindaje. Gracias al altamente desarrollado motor de combustión instalado, sirve como el suministrador de recursos más económico entre planetas, y el más eficaz en asaltos a mundos hostiles.";
$LOCA["es"]["LONG_204"] = "Esta es la primera nave de combate que construirán todos los emperadores. El cazador ligero es una nave ágil, pero vulnerable cuando está solo. En grandes cantidades, pueden convertirse en una gran amenaza para cualquier imperio. Son los primeros en acompañar a los cargueros pequeños y grandes hacia planetas hostiles con defensas menores.";
$LOCA["es"]["LONG_205"] = "Al desarrollar el cazador pesado, los investigadores llegaron a un punto en el que los motores convencionales ya no ofrecían un rendimiento suficiente. Para mover la nave de forma óptima, se utilizó por primera vez el motor de impulso. Esto aumentó los costes, pero también abrió nuevas posibilidades. Al usar este motor, quedaba más energía para armas y escudos; además, se utilizaron materiales de alta calidad para esta nueva familia de cazadores. Con estos cambios, el cazador pesado representa una nueva era en la tecnología naval y es la base de la tecnología de cruceros.<br/>
Ligeramente más grande que el cazador ligero, el cazador pesado tiene cascos más gruesos, que proporcionan más protección, y un armamento más potente.";
$LOCA["es"]["LONG_206"] = "Con el desarrollo del láser pesado y del cañón iónico, los cazadores ligeros y pesados sufrieron un número alarmantemente alto de derrotas que aumentaba con cada asalto. A pesar de muchas modificaciones, cambios en la fuerza de las armas y en el blindaje, no se podía aumentar lo bastante rápido para contrarrestar eficazmente estas nuevas medidas defensivas. Por tanto, se decidió construir una nueva clase de nave que combinara más blindaje y más potencia de fuego. Como resultado de años de investigación y desarrollo, nació el crucero.<br/>
Los cruceros están blindados casi tres veces más que los cazadores pesados y poseen más del doble de potencia de fuego que cualquier nave de combate existente. También poseen velocidades que superaban con creces a cualquier nave espacial jamás construida. Durante casi un siglo, los cruceros dominaron el universo. Sin embargo, con el desarrollo de los cañones de Gauss y las torretas de plasma, su predominio terminó. Todavía se usan hoy contra grupos de cazadores, pero no de forma tan predominante como antes.";
$LOCA["es"]["LONG_207"] = "Cuando se hizo evidente que el crucero estaba perdiendo terreno frente al creciente número de estructuras de defensa a las que se enfrentaba, y con las pérdidas de naves en misiones a niveles inaceptables, se decidió construir una nave que pudiera enfrentarse a ese mismo tipo de estructuras de defensa con la menor pérdida posible. Tras un extenso desarrollo, nació el acorazado. Construido para resistir las batallas más grandes, el acorazado cuenta con grandes bodegas de carga, cañones pesados y una alta velocidad de hiperimpulso. Una vez desarrollado, resultó ser la columna vertebral de la flota de todo emperador asaltante.";
$LOCA["es"]["LONG_208"] = "En el siglo XX, el hombre decidió ir tras las estrellas. Primero fue el aterrizaje en la Luna. Después se construyó una estación espacial. Marte fue colonizado poco después. Pronto se determinó que nuestro crecimiento dependía de colonizar otros mundos. Científicos e ingenieros de todo el mundo se reunieron para desarrollar el mayor logro de la humanidad. Nació la nave de colonización. Esta nave se utiliza para preparar un planeta recién descubierto para la colonización. Una vez llega a su destino, la nave se transforma instantáneamente en espacio habitable para ayudar a poblar y extraer recursos del nuevo mundo. Cada imperio, incluido el planeta principal, puede colonizar un máximo de 9 planetas.";
$LOCA["es"]["LONG_209"] = "El combate espacial alcanzó escalas cada vez mayores. Miles de naves fueron destruidas y los recursos de sus restos parecían perdidos para siempre en los campos de escombros. Los cargueros normales no podían acercarse lo suficiente a estos campos sin arriesgar daños considerables.</br>
Un desarrollo reciente en las tecnologías de escudos evitó eficazmente este problema. Se creó una nueva clase de naves similar a los transportadores: los recicladores. Sus esfuerzos ayudaron a recoger los recursos que se creían perdidos y luego recuperarlos. Los escombros ya no suponían ningún peligro real gracias a los nuevos escudos.";
$LOCA["es"]["LONG_210"] = "Las sondas de espionaje son pequeños drones ágiles que proporcionan datos sobre flotas y planetas. Equipadas con motores especialmente diseñados, pueden cubrir vastas distancias en solo unos minutos. Una vez en órbita alrededor del planeta objetivo, recopilan datos rápidamente y transmiten el informe de vuelta a través de tu red de espacio profundo para su evaluación. Pero hay un riesgo en el aspecto de la recopilación de información. Durante el tiempo en que el informe se transmite de vuelta a tu red, la señal puede ser detectada por el objetivo y las sondas pueden ser destruidas.";
$LOCA["es"]["LONG_211"] = "A lo largo de los siglos, a medida que las defensas empezaban a ser más grandes y sofisticadas, las flotas comenzaban a ser destruidas a un ritmo alarmante. Se decidió que se necesitaba una nueva nave para romper las defensas y garantizar los máximos resultados. Tras años de investigación y desarrollo, se creó el bombardero.<br/>
Usando equipos de puntería guiados por láser y bombas de plasma, el bombardero localiza y destruye cualquier mecanismo de defensa que pueda encontrar. En cuanto el motor de hiperespacio se desarrolla hasta el nivel 8, el bombardero se reequipa con el motor de hiperespacio y puede volar a mayores velocidades.";
$LOCA["es"]["LONG_212"] = "Los científicos descubrieron un método para transmitir energía eléctrica a la colonia utilizando satélites especialmente diseñados en una órbita geosíncrona. Los satélites solares recogen la energía solar y la transmiten a una estación terrestre usando tecnología láser avanzada. La eficiencia de un satélite solar depende de la intensidad de la radiación solar que recibe. En principio, la producción de energía en órbitas más cercanas al sol es mayor que en los planetas situados en órbitas lejanas al sol.<br/>
Debido a su buena relación coste/rendimiento, los satélites solares pueden resolver muchos problemas de energía. Pero cuidado: los satélites solares pueden ser destruidos fácilmente en batalla.";
$LOCA["es"]["LONG_213"] = "El destructor es el resultado de años de trabajo y desarrollo. Con el desarrollo de las estrellas de la muerte, se decidió que se necesitaba una clase de nave para defenderse de un arma tan masiva. Gracias a sus sensores de localización mejorados, cañones iónicos de phalanx múltiple, cañones de Gauss y torretas de plasma, el destructor resultó ser una de las naves más temibles jamás creadas.<br/>
Debido a que el destructor es muy grande, su maniobrabilidad es muy limitada, lo que lo convierte más en una estación de batalla que en una nave de combate. La falta de maniobrabilidad se compensa con su enorme potencia de fuego, pero también cuesta cantidades significativas de deuterio construirlo y operarlo.";
$LOCA["es"]["LONG_214"] = "La estrella de la muerte es la nave más poderosa jamás creada. Esta nave del tamaño de una luna es la única nave que puede verse a simple vista desde el suelo. Cuando la divisas, desgraciadamente, ya es demasiado tarde para hacer nada.<br/>
Armada con un gigantesco cañón de gravitones, el sistema de armas más avanzado jamás creado en el universo, esta nave masiva no solo tiene la capacidad de destruir flotas y defensas enteras, sino también de destruir lunas completas. Solo los imperios más avanzados tienen la capacidad de construir una nave de este tamaño colosal.";
$LOCA["es"]["LONG_215"] = "Esta nave es una de las naves de combate más avanzadas jamás desarrolladas, y es especialmente letal a la hora de destruir flotas atacantes. Con sus cañones láser mejorados a bordo y su avanzado motor de hiperespacio, el crucero de batalla es una fuerza seria a tener en cuenta en cualquier ataque. Debido al diseño de la nave y a su gran sistema de armas, las bodegas de carga tuvieron que reducirse, pero esto se compensa con un menor consumo de combustible.";

$LOCA["es"]["LONG_401"] = "Tu primera línea básica de defensa. Son simples instalaciones de lanzamiento terrestres que disparan misiles con ojivas convencionales contra objetivos enemigos atacantes. Como son baratos de construir y no requieren investigación, son muy adecuados para defender asaltos, pero pierden eficacia al defender de ataques a mayor escala. Una vez que comienzas la construcción de sistemas de armas de defensa más avanzados, los lanzamisiles se convierten en simple carne de cañón para que tus armas más dañinas inflijan un mayor daño durante más tiempo.";
$LOCA["es"]["LONG_402"] = "A medida que la tecnología se desarrollaba y se creaban naves más sofisticadas, se determinó que se necesitaba una línea de defensa más fuerte para contrarrestar los ataques. A medida que avanzaba la tecnología láser, se diseñó una nueva arma para proporcionar el siguiente nivel de defensa. Los láseres ligeros son armas terrestres simples que utilizan sistemas de puntería especiales para rastrear al enemigo y disparar un láser de alta intensidad diseñado para cortar el casco del objetivo. Para mantener la rentabilidad, se equiparon con un sistema de escudo mejorado; sin embargo, la integridad estructural es la misma que la del lanzamisiles.";
$LOCA["es"]["LONG_403"] = "El láser pesado es una versión práctica y mejorada del láser ligero. Al estar más equilibrado que el láser ligero con una composición de aleación mejorada, utiliza haces más potentes y densos, e incluso mejores sistemas de puntería a bordo.";
$LOCA["es"]["LONG_404"] = "Durante mucho tiempo, las armas de proyectiles fueron consideradas anticuadas a raíz de la moderna tecnología termonuclear y energética, y debido al desarrollo del hiperimpulso y del blindaje mejorado. Así fue hasta que la misma tecnología energética que una vez las envejeció ayudó a recuperar su posición establecida.<br/>
Un cañón de Gauss es una versión grande del acelerador de partículas. Misiles extremadamente pesados son acelerados con una enorme fuerza electromagnética y tienen velocidades de salida que hacen que la suciedad que rodea al misil arda en el cielo. Esta arma es tan poderosa al disparar que crea una onda de choque sónica. El blindaje y los escudos modernos apenas pueden resistir la fuerza; a menudo el objetivo es completamente atravesado por la potencia del misil. Las estructuras de defensa se desactivan en cuanto han resultado demasiado dañadas.";
$LOCA["es"]["LONG_405"] = "Un cañón iónico es un arma que dispara haces de iones (partículas con carga positiva o negativa). El cañón iónico es en realidad un tipo de cañón de partículas; solo que las partículas utilizadas están ionizadas. Debido a sus cargas eléctricas, también tienen el potencial de desactivar dispositivos electrónicos y cualquier otra cosa que tenga una fuente de energía eléctrica o similar, utilizando un fenómeno conocido como pulso electromagnético (efecto EMP). Gracias al sistema de escudo altamente mejorado del cañón, este proporciona una protección mejorada para tus armas de defensa más grandes y destructivas.";
$LOCA["es"]["LONG_406"] = "Uno de los sistemas de armas de defensa más avanzados jamás desarrollados, la torreta de plasma utiliza una gran celda de combustible de reactor nuclear para alimentar un acelerador electromagnético que dispara un pulso, o toroide, de plasma. Durante su funcionamiento, la torreta de plasma primero fija un objetivo y comienza el proceso de disparo. Se crea una esfera de plasma en el núcleo de la torreta sobrecalentando y comprimiendo gases, despojándolos de sus iones. Una vez que el gas está sobrecalentado, comprimido y se ha creado la esfera de plasma, se carga en el acelerador electromagnético, que se energiza. Una vez completamente energizado, el acelerador se activa, lo que resulta en el lanzamiento de la esfera de plasma a una velocidad extremadamente alta hacia el objetivo previsto. Desde la perspectiva del objetivo, la bola de plasma azulada que se aproxima es impresionante, pero una vez impacta, causa una destrucción instantánea.";
$LOCA["es"]["LONG_407"] = "Colonizar nuevos mundos trajo consigo un nuevo peligro: los desechos espaciales. Un gran asteroide podría acabar fácilmente con el mundo y todos sus habitantes. Los avances en la tecnología de escudos proporcionaron a los científicos una forma de desarrollar un escudo para proteger un planeta entero no solo de los desechos espaciales, sino también, como se aprendió, de un ataque enemigo. Al crear un gran campo electromagnético alrededor del planeta, los desechos espaciales que normalmente habrían destruido el planeta eran desviados, y los ataques de imperios enemigos eran frustrados. Los primeros generadores eran grandes y el escudo proporcionaba una protección moderada, pero más tarde se descubrió que los escudos pequeños no ofrecían protección frente a ataques a mayor escala. La pequeña cúpula de escudo fue el preludio de un sistema de escudo planetario más fuerte y avanzado que estaba por llegar.";
$LOCA["es"]["LONG_408"] = "La gran cúpula de escudo es el siguiente paso en el avance de los escudos planetarios; es el resultado de años de trabajo mejorando la pequeña cúpula de escudo. Construida para resistir un bombardeo mayor de fuego enemigo al proporcionar un campo electromagnético más energizado, las grandes cúpulas ofrecen un período de protección más largo antes de colapsar.";
$LOCA["es"]["LONG_502"] = "Los misiles antibalísticos (ABM) son tu única línea de defensa cuando tu planeta o luna es atacado por misiles interplanetarios (IPM). Cuando se detecta un lanzamiento de IPM, estos misiles se arman automáticamente, procesan un código de lanzamiento en sus ordenadores de vuelo, fijan como objetivo el IPM entrante y se lanzan para interceptarlo. Durante el vuelo, el IPM objetivo es rastreado constantemente y se aplican correcciones de rumbo hasta que el ABM alcanza el objetivo y destruye el IPM atacante. Cada ABM destruye un IPM entrante.";
$LOCA["es"]["LONG_503"] = "Los misiles interplanetarios (IPM) son tu arma ofensiva para destruir las defensas de tu objetivo. Usando tecnología de seguimiento de última generación, cada misil fija como objetivo un cierto número de defensas para su destrucción. Equipados con una bomba de antimateria, liberan una fuerza destructiva tan severa que los escudos y defensas destruidos no pueden repararse. La única forma de contrarrestar estos misiles es con ABM.";

?>
