<?php

// Description détaillée des objets.

$LOCA["fr"]["LONG_1"] = "Le métal est la ressource principale utilisée pour fonder votre empire. À plus grande profondeur, les mines peuvent produire davantage de métal exploitable pour la construction de bâtiments, de vaisseaux, de systèmes de défense et de recherches. À mesure que les mines forent plus profondément, davantage d'énergie est requise pour une production maximale. Comme le métal est la plus abondante de toutes les ressources disponibles, sa valeur est considérée comme la plus faible de toutes les ressources pour le commerce.";
$LOCA["fr"]["LONG_2"] = "Les mines de cristal fournissent la principale ressource utilisée pour produire des circuits électroniques et certains composés d'alliage. L'extraction du cristal consomme environ une fois et demie plus d'énergie que l'extraction du métal, ce qui rend le cristal plus précieux. Presque tous les vaisseaux et tous les bâtiments nécessitent du cristal. La plupart des cristaux nécessaires à la construction de vaisseaux spatiaux sont toutefois très rares et, comme le métal, ne peuvent être trouvés qu'à une certaine profondeur. Par conséquent, construire des mines dans des strates plus profondes augmentera la quantité de cristal produite.";
$LOCA["fr"]["LONG_3"] = "Le deutérium est également appelé hydrogène lourd. C'est un isotope stable de l'hydrogène dont l'abondance naturelle dans les océans des colonies est d'environ un atome pour 6500 atomes d'hydrogène (~154 ppm). Le deutérium représente ainsi environ 0,015 % (sur une base pondérale, 0,030 %) du total. Le deutérium est traité par des synthétiseurs spéciaux qui peuvent séparer l'eau du deutérium à l'aide de centrifugeuses spécialement conçues. L'amélioration du synthétiseur permet d'augmenter la quantité de dépôts de deutérium traités. Le deutérium est utilisé lors des scans de phalange de détection, de l'observation des galaxies, comme carburant pour les vaisseaux et pour effectuer des améliorations de recherche spécialisées.";
$LOCA["fr"]["LONG_4"] = "Des panneaux solaires gigantesques sont utilisés pour générer de l'énergie pour les mines et le synthétiseur de deutérium. À mesure que la centrale solaire est améliorée, la surface des cellules photovoltaïques couvrant la planète augmente, ce qui se traduit par une production d'énergie plus élevée sur les réseaux électriques de votre planète.";
$LOCA["fr"]["LONG_12"] = "Dans les centrales à fusion, les noyaux d'hydrogène sont fusionnés en noyaux d'hélium sous une température et une pression énormes, libérant d'immenses quantités d'énergie. Pour chaque gramme de deutérium consommé, il est possible de produire jusqu'à 41,32*10^-13 joule d'énergie ; avec 1 g, vous êtes en mesure de produire 172 MWh d'énergie.<br/>
Les complexes de réacteurs plus grands utilisent plus de deutérium et peuvent produire plus d'énergie par heure. L'effet énergétique peut être augmenté en recherchant la technologie énergie.<br/>
La production d'énergie de la centrale à fusion est calculée comme suit :<br/>
30 * [Niveau Centrale à fusion] * (1,05 + [Niveau Technologie énergie] * 0,01) ^ [Niveau Centrale à fusion]";
$LOCA["fr"]["LONG_14"] = "L'objectif principal de l'usine de robots est la production de robots de construction dernier cri. Chaque amélioration de l'usine de robots se traduit par la production de robots plus rapides, ce qui permet de réduire le temps nécessaire à la construction de bâtiments.";
$LOCA["fr"]["LONG_15"] = "Une nanomachine, également appelée nanite, est un dispositif mécanique ou électromécanique dont les dimensions se mesurent en nanomètres (millièmes de millimètre, ou unités de 10^-9 mètre). La taille microscopique des nanomachines se traduit par une vitesse de fonctionnement plus élevée. Cette usine produit des nanomachines qui constituent l'évolution ultime de la technologie robotique. Une fois construite, chaque amélioration réduit considérablement le temps de production des bâtiments, des vaisseaux et des structures défensives.";
$LOCA["fr"]["LONG_21"] = "Le chantier spatial planétaire est responsable de la construction des vaisseaux spatiaux et des mécanismes de défense. À mesure que le chantier spatial est amélioré, il peut produire une plus grande variété de véhicules à un rythme bien plus élevé. Si une usine de nanites est présente sur la planète, la vitesse à laquelle les vaisseaux sont construits est massivement augmentée.";
$LOCA["fr"]["LONG_22"] = "Cette installation de stockage géante est utilisée pour stocker le minerai de métal. Chaque niveau d'amélioration augmente la quantité de minerai de métal pouvant être stockée. Si les entrepôts sont pleins, aucun métal supplémentaire ne sera extrait.";
$LOCA["fr"]["LONG_23"] = "Le cristal non traité sera stocké dans ces immenses halls de stockage en attendant. Chaque niveau d'amélioration augmente la quantité de cristal pouvant être stockée. Si les entrepôts de cristal sont pleins, aucun cristal supplémentaire ne sera extrait.";
$LOCA["fr"]["LONG_24"] = "Le réservoir de deutérium sert à stocker le deutérium nouvellement synthétisé. Une fois traité par le synthétiseur, il est acheminé vers ce réservoir pour une utilisation ultérieure. Chaque amélioration du réservoir augmente la capacité de stockage totale. Une fois la capacité atteinte, aucun deutérium supplémentaire ne sera synthétisé.";
$LOCA["fr"]["LONG_31"] = "Partie essentielle de tout empire, les laboratoires de recherche sont l'endroit où de nouvelles technologies sont découvertes et où les technologies plus anciennes sont améliorées. Avec chaque niveau de laboratoire de recherche construit, la vitesse à laquelle les nouvelles technologies sont recherchées augmente, tout en débloquant de nouvelles technologies à rechercher. Afin de mener les recherches le plus rapidement possible, des scientifiques sont immédiatement dépêchés vers la colonie pour commencer le travail et le développement. De cette manière, les connaissances sur les nouvelles technologies peuvent facilement être diffusées dans tout l'empire.";
$LOCA["fr"]["LONG_33"] = "Avec l'augmentation des constructions sur les planètes, même l'espace de vie de la colonie devient de plus en plus limité. Les méthodes traditionnelles telles que les constructions en hauteur et souterraines deviennent de plus en plus insuffisantes. Un petit groupe de physiciens de haute énergie et d'ingénieurs en nanotechnologie a finalement trouvé la solution : le terraformage.<br/>
En utilisant d'énormes quantités d'énergie, le terraformeur peut rendre cultivables des étendues entières de terre, voire des continents. Ce bâtiment abrite la production de nanites créées spécifiquement à cet effet, qui garantissent une qualité de sol constante sur toute la surface.";
$LOCA["fr"]["LONG_34"] = "Le dépôt d'alliance fournit du carburant aux flottes amies en orbite qui aident à la défense. Pour chaque niveau d'amélioration du dépôt d'alliance, une demande spéciale de deutérium par heure peut être envoyée à une flotte en orbite.";
$LOCA["fr"]["LONG_41"] = "Une lune n'a pas d'atmosphère, une base lunaire doit donc d'abord être construite avant qu'un établissement puisse être installé. Elle fournit ensuite de l'oxygène, du chauffage et de la gravité. Avec chaque niveau construit, une plus grande zone de vie et de développement est fournie dans la biosphère. Chaque niveau construit permet trois emplacements pour d'autres bâtiments. À chaque niveau, la base lunaire occupe elle-même un emplacement.<br/>
Une fois construite, la base lunaire ne peut pas être démolie.";
$LOCA["fr"]["LONG_42"] = "Utilisant des capteurs haute résolution, la phalange de détection scanne d'abord le spectre de la lumière, la composition des gaz et les émissions de rayonnement d'un monde lointain et transmet les données à un superordinateur pour traitement. Une fois les informations obtenues, le superordinateur compare les changements du spectre, de la composition des gaz et des émissions de rayonnement à un graphique de référence des changements connus du spectre créés par divers mouvements de vaisseaux. Les données résultantes affichent ensuite l'activité de toute flotte à portée de la phalange. Pour éviter que le superordinateur ne surchauffe pendant le processus, il est refroidi en utilisant 5k de deutérium traité.<br/>
Pour utiliser la phalange, cliquez sur n'importe quelle planète de la vue Galaxie située à portée de vos capteurs.";
$LOCA["fr"]["LONG_43"] = "Une porte de saut est un système de transmetteurs géants capable d'envoyer même les plus grandes flottes vers une porte de réception n'importe où dans l'univers sans perte de temps. Utilisant une technologie similaire à celle d'un trou de ver pour effectuer le saut, le deutérium n'est pas requis. Une période de recharge de quelques minutes doit s'écouler entre les sauts pour permettre la régénération. Le transport de ressources à travers la porte n'est pas non plus possible. Chaque niveau d'amélioration peut réduire le temps de recharge de la porte de saut.";
$LOCA["fr"]["LONG_44"] = "Les silos à missiles sont utilisés pour construire, stocker et lancer des missiles interplanétaires et anti-balistiques. Avec chaque niveau du silo, cinq missiles interplanétaires ou dix missiles anti-balistiques peuvent être stockés. Un missile interplanétaire utilise le même espace que deux missiles anti-balistiques. Le stockage simultané de missiles interplanétaires et anti-balistiques dans le même silo est autorisé.";

$LOCA["fr"]["LONG_106"] = "La technologie d'espionnage est, dans un premier temps, une avancée de la technologie des capteurs. Plus cette technologie est avancée, plus l'utilisateur reçoit d'informations sur les activités de son environnement.
Les différences entre votre propre niveau d'espionnage et les niveaux d'espionnage adverses sont cruciales pour les sondes. Plus votre propre technologie d'espionnage est avancée, plus le rapport peut recueillir d'informations et plus la probabilité que vos activités d'espionnage soient découvertes est faible. Plus vous envoyez de sondes lors d'une seule mission, plus elles peuvent recueillir de détails sur la planète cible. Mais en même temps, cela augmente également le risque de découverte.
La technologie d'espionnage améliore également les chances de localiser des flottes étrangères. Le niveau d'espionnage est essentiel pour déterminer cela. À partir du niveau 2, le nombre total exact de vaisseaux attaquants est affiché en plus de la notification d'attaque normale. Et à partir du niveau 4, le type des vaisseaux attaquants ainsi que le nombre total sont affichés, et à partir du niveau 8, le nombre exact des différents types de vaisseaux est affiché.
Cette technologie est indispensable pour une attaque à venir, car elle vous informe si la flotte victime dispose ou non d'une défense. C'est pourquoi cette technologie devrait être recherchée très tôt.";
$LOCA["fr"]["LONG_108"] = "Une fois lancées en mission, les flottes sont contrôlées principalement par une série d'ordinateurs situés sur la planète d'origine. Ces ordinateurs massifs calculent l'heure exacte d'arrivée, contrôlent les corrections de cap si nécessaire, calculent les trajectoires et régulent les vitesses de vol.<br/>
Avec chaque niveau recherché, l'ordinateur de vol est amélioré pour permettre le lancement d'un emplacement supplémentaire. La technologie informatique doit être développée en continu tout au long de la construction de votre empire.";
$LOCA["fr"]["LONG_109"] = "La technologie des armes est une technologie de recherche clé et est essentielle à votre survie face aux empires ennemis. Avec chaque niveau de technologie des armes recherché, les systèmes d'armes des vaisseaux et vos mécanismes de défense deviennent de plus en plus efficaces. Chaque niveau augmente la puissance de base de vos armes de 10 % de la valeur de base.";
$LOCA["fr"]["LONG_110"] = "Avec l'invention du générateur de magnétosphère, les scientifiques ont appris qu'un bouclier artificiel pouvait être produit pour protéger l'équipage des vaisseaux spatiaux non seulement du rude environnement de rayonnement solaire de l'espace profond, mais aussi pour fournir une protection contre les tirs ennemis lors d'une attaque. Une fois que les scientifiques ont finalement perfectionné la technologie, un générateur de magnétosphère a été installé sur tous les vaisseaux et systèmes de défense.<br/>
À mesure que la technologie progresse à chaque niveau, le générateur de magnétosphère est amélioré, ce qui fournit 10 % de force supplémentaire à la valeur de base des boucliers.";
$LOCA["fr"]["LONG_111"] = "L'environnement de l'espace profond est rude. Les pilotes et les équipages lors de diverses missions devaient non seulement faire face à un rayonnement solaire intense, mais aussi à la perspective d'être heurtés par des débris spatiaux, ou détruits par les tirs ennemis lors d'une attaque. Avec la découverte d'un alliage d'aluminium-lithium et de carbure de titane, qui s'est avéré à la fois léger et durable, l'équipage a bénéficié d'un certain degré de protection. Avec chaque niveau de technologie d'armure développé, un alliage de meilleure qualité est produit, ce qui augmente la résistance de l'armure de 10 %.";
$LOCA["fr"]["LONG_113"] = "À mesure que divers domaines de recherche progressaient, il a été découvert que la technologie actuelle de distribution d'énergie n'était pas suffisante pour commencer certaines recherches spécialisées. Avec chaque amélioration de votre technologie énergie, de nouvelles recherches peuvent être menées, ce qui débloque le développement de vaisseaux et de défenses plus sophistiqués.";
$LOCA["fr"]["LONG_114"] = "En théorie, l'idée du voyage hyperspatial repose sur l'existence d'une dimension distincte et adjacente. Une fois activé, un moteur hyperspatial fait passer le vaisseau dans cette autre dimension, où il peut parcourir de vastes distances en un temps considérablement réduit par rapport au temps qu'il faudrait dans l'espace « normal ». Une fois qu'il atteint le point de l'hyperespace correspondant à sa destination dans l'espace réel, il en resurgit.";
$LOCA["fr"]["LONG_115"] = "Le moteur à combustion est la plus ancienne des technologies, mais il est toujours utilisé. Avec le moteur à combustion, les gaz d'échappement sont formés à partir de propergols transportés dans le vaisseau avant utilisation. Dans une chambre fermée, les pressions sont égales dans chaque direction et aucune accélération ne se produit. Si une ouverture est prévue au bas de la chambre, la pression n'est alors plus opposée de ce côté. La pression restante donne une poussée résultante du côté opposé à l'ouverture, qui propulse le vaisseau vers l'avant en expulsant les gaz d'échappement vers l'arrière à une vitesse extrêmement élevée.<br/>
Avec chaque niveau de moteur à combustion développé, la vitesse des petits et grands transporteurs, des chasseurs légers, des recycleurs et des sondes d'espionnage est augmentée de 10 %.";
$LOCA["fr"]["LONG_117"] = "Le moteur à impulsion est basé sur le principe de recul, par lequel l'émission stimulée de rayonnement est principalement produite comme déchet de la fusion du cœur pour gagner de l'énergie. De plus, d'autres masses peuvent être injectées. Avec chaque niveau de moteur à impulsion développé, la vitesse des bombardiers, des croiseurs, des chasseurs lourds et des vaisseaux de colonisation est augmentée de 20 % de la valeur de base. De plus, les petits transporteurs sont équipés de moteurs à impulsion dès que leur niveau de recherche atteint 5. Dès que la recherche du moteur à impulsion a atteint le niveau 17, les recycleurs sont rééquipés de moteurs à impulsion.<br/>
Les missiles interplanétaires voyagent également plus loin à chaque niveau.";
$LOCA["fr"]["LONG_118"] = "Dans l'environnement immédiat du vaisseau, l'espace est déformé afin que de longues distances puissent être parcourues très rapidement. Plus le moteur hyperspatial est développé, plus la déformation de l'espace est forte, ce qui augmente la vitesse des vaisseaux qui en sont équipés (croiseurs de bataille, vaisseaux de bataille, destructeurs, morts noires, éclaireurs et faucheurs) de 30 % par niveau. De plus, le bombardier est construit avec un moteur hyperspatial dès que la recherche atteint le niveau 8. Dès que la recherche du moteur hyperspatial atteint le niveau 15, le recycleur est rééquipé d'un moteur hyperspatial.";
$LOCA["fr"]["LONG_120"] = "Les lasers (amplification de la lumière par émission stimulée de rayonnement) produisent une émission intense et riche en énergie de lumière cohérente. Ces dispositifs peuvent être utilisés dans toutes sortes de domaines, des ordinateurs optiques aux armes laser lourdes, qui traversent sans effort la technologie d'armure. La technologie laser fournit une base importante pour la recherche d'autres technologies d'armes.";
$LOCA["fr"]["LONG_121"] = "Les ions peuvent être concentrés et accélérés en un faisceau mortel. Ces faisceaux peuvent ensuite infliger des dégâts énormes. Nos scientifiques ont également développé une technique qui réduira nettement les coûts de déconstruction des bâtiments et des systèmes.";
$LOCA["fr"]["LONG_122"] = "Un développement supplémentaire de la technologie ionique qui n'accélère pas les ions mais un plasma à haute énergie, qui peut ensuite infliger des dégâts dévastateurs à l'impact avec un objet. Nos scientifiques ont également trouvé un moyen d'améliorer sensiblement l'extraction du métal et du cristal en utilisant cette technologie.";
$LOCA["fr"]["LONG_123"] = "Il s'agit de votre réseau spatial profond pour communiquer les résultats de recherche à vos colonies. Avec le RRI, des temps de recherche plus rapides peuvent être obtenus en reliant les laboratoires de recherche du plus haut niveau, égal au niveau du RRI développé.<br/>
Pour fonctionner, chaque colonie doit être capable de mener la recherche de manière indépendante.";
$LOCA["fr"]["LONG_124"] = "La technologie d'expédition couvre diverses technologies de scan et permet d'équiper des vaisseaux de différentes classes d'un module de recherche. Il contient une base de données, un petit laboratoire mobile, ainsi que diverses biocellules et conteneurs d'échantillons. Pour la sécurité du vaisseau lors de l'exploration d'objets dangereux, le module de recherche est équipé d'une alimentation électrique autonome et d'un générateur de champ d'énergie, qui peut entourer le module de recherche d'un puissant champ d'énergie dans des situations extrêmes.";
$LOCA["fr"]["LONG_199"] = "Un graviton est une particule élémentaire sans masse et sans charge. Il détermine la force gravitationnelle. En tirant une charge concentrée de gravitons, un champ gravitationnel artificiel peut être construit. À la manière d'un trou noir, il attire la masse vers lui. Il peut ainsi détruire des vaisseaux et même des lunes entières. Pour produire une quantité suffisante de gravitons, d'énormes quantités d'énergie sont requises. La recherche sur les gravitons est requise pour construire une mort noire destructrice.";

$LOCA["fr"]["LONG_202"] = "Les transporteurs ont à peu près la taille des chasseurs, mais ils renoncent aux moteurs hautes performances et à l'armement embarqué au profit de leur capacité de fret. Par conséquent, un transporteur ne devrait être envoyé au combat que lorsqu'il est accompagné de vaisseaux prêts au combat.<br/>
Dès que le moteur à impulsion atteint le niveau de recherche 5, le petit transporteur voyage à une vitesse de base accrue et est équipé d'un moteur à impulsion.";
$LOCA["fr"]["LONG_203"] = "Au fil du temps, les raids sur les colonies ont permis de capturer des quantités de plus en plus importantes de ressources. En conséquence, de petits transporteurs étaient envoyés en masse pour compenser les captures plus importantes. On a rapidement compris qu'une nouvelle classe de vaisseaux était nécessaire pour maximiser les ressources capturées lors des raids, tout en restant
rentable. Après de nombreux développements, le grand transporteur est né.<br/>
Pour maximiser les ressources pouvant être stockées dans les cales, ce vaisseau possède peu d'armes ou d'armure. Grâce au moteur à combustion hautement développé installé, il sert de fournisseur de ressources le plus économique entre les planètes, et il est le plus efficace lors des raids sur des mondes hostiles.";
$LOCA["fr"]["LONG_204"] = "C'est le premier vaisseau de combat que tous les empereurs construiront. Le chasseur léger est un vaisseau agile, mais vulnérable lorsqu'il est seul. En grand nombre, ils peuvent devenir une grande menace pour n'importe quel empire. Ils sont les premiers à accompagner les petits et grands transporteurs vers des planètes hostiles dotées de défenses mineures.";
$LOCA["fr"]["LONG_205"] = "En développant le chasseur lourd, les chercheurs ont atteint un point où les moteurs conventionnels ne fournissaient plus des performances suffisantes. Afin de déplacer le vaisseau de manière optimale, le moteur à impulsion a été utilisé pour la première fois. Cela a augmenté les coûts, mais a aussi ouvert de nouvelles possibilités. Grâce à l'utilisation de ce moteur, il restait plus d'énergie pour les armes et les boucliers ; de plus, des matériaux de haute qualité ont été utilisés pour cette nouvelle famille de chasseurs. Avec ces changements, le chasseur lourd représente une nouvelle ère dans la technologie des vaisseaux et constitue la base de la technologie des croiseurs.<br/>
Légèrement plus grand que le chasseur léger, le chasseur lourd possède des coques plus épaisses, offrant plus de protection, et un armement plus puissant.";
$LOCA["fr"]["LONG_206"] = "Avec le développement du laser lourd et du canon à ions, les chasseurs légers et lourds ont subi un nombre alarmant de défaites qui augmentait à chaque raid. Malgré de nombreuses modifications, la puissance des armes et les changements d'armure ne pouvaient pas être augmentés assez rapidement pour contrer efficacement ces nouvelles mesures défensives. Par conséquent, il a été décidé de construire une nouvelle classe de vaisseaux combinant plus d'armure et plus de puissance de feu. À la suite d'années de recherche et de développement, le croiseur est né.<br/>
Les croiseurs sont blindés près de trois fois plus que les chasseurs lourds et possèdent plus de deux fois la puissance de feu de tout vaisseau de combat existant. Ils possèdent également des vitesses qui surpassent de loin tous les vaisseaux spatiaux jamais construits. Pendant près d'un siècle, les croiseurs ont dominé l'univers. Cependant, avec le développement des canons de Gauss et des lanceurs de plasma, leur prédominance a pris fin. Ils sont encore utilisés aujourd'hui contre les groupes de chasseurs, mais pas aussi prédominants qu'avant.";
$LOCA["fr"]["LONG_207"] = "Lorsqu'il est devenu évident que le croiseur perdait du terrain face au nombre croissant de structures défensives auxquelles il était confronté, et avec des pertes de vaisseaux lors des missions atteignant des niveaux inacceptables, il a été décidé de construire un vaisseau capable d'affronter ces mêmes types de structures défensives avec le moins de pertes possible. Après un développement approfondi, le vaisseau de bataille est né. Conçu pour résister aux plus grandes batailles, le vaisseau de bataille dispose de grands espaces de chargement, de canons lourds et d'une vitesse hyperspatiale élevée. Une fois développé, il s'est finalement avéré être l'épine dorsale de la flotte de chaque empereur pillard.";
$LOCA["fr"]["LONG_208"] = "Au XXe siècle, l'homme a décidé d'aller vers les étoiles. D'abord, ce fut l'alunissage. Ensuite, une station spatiale a été construite. Mars a été colonisée peu de temps après. Il a rapidement été déterminé que notre croissance dépendait de la colonisation d'autres mondes. Des scientifiques et des ingénieurs du monde entier se sont réunis pour développer la plus grande réussite de l'homme. Le vaisseau de colonisation est né. Ce vaisseau est utilisé pour préparer une planète nouvellement découverte à la colonisation. Une fois arrivé à destination, le vaisseau est instantanément transformé en espace de vie habitable pour aider à peupler et à exploiter le nouveau monde. Chaque empire, y compris la planète principale, peut coloniser un maximum de 9 planètes.";
$LOCA["fr"]["LONG_209"] = "Les combats dans l'espace ont pris des proportions toujours plus grandes. Des milliers de vaisseaux ont été détruits et les ressources de leurs restes semblaient perdues à jamais dans les champs de débris. Les transporteurs normaux ne pouvaient pas s'approcher assez de ces champs sans risquer des dégâts substantiels.</br>
Un développement récent des technologies de bouclier a contourné efficacement ce problème. Une nouvelle classe de vaisseaux a été créée, semblable aux transporteurs : les recycleurs. Leurs efforts ont permis de récupérer les ressources que l'on croyait perdues, puis de les récupérer. Les débris ne représentaient plus aucun danger réel grâce aux nouveaux boucliers.";
$LOCA["fr"]["LONG_210"] = "Les sondes d'espionnage sont de petits drones agiles qui fournissent des données sur les flottes et les planètes. Équipées de moteurs spécialement conçus, elles peuvent parcourir de vastes distances en quelques minutes seulement. Une fois en orbite autour de la planète cible, elles collectent rapidement des données et transmettent le rapport via votre réseau spatial profond pour évaluation. Mais il y a un risque pour la collecte de renseignements. Pendant que le rapport est transmis à votre réseau, le signal peut être détecté par la cible et les sondes peuvent être détruites.";
$LOCA["fr"]["LONG_211"] = "Au fil des siècles, à mesure que les défenses devenaient plus grandes et plus sophistiquées, les flottes commençaient à être détruites à un rythme alarmant. Il a été décidé qu'un nouveau vaisseau était nécessaire pour briser les défenses et garantir des résultats maximaux. Après des années de recherche et de développement, le bombardier a été créé.<br/>
Grâce à un équipement de ciblage guidé par laser et à des bombes à plasma, le bombardier traque et détruit tout mécanisme de défense qu'il peut trouver. Dès que le moteur hyperspatial est développé au niveau 8, le bombardier est rééquipé avec le moteur hyperspatial et peut voler à des vitesses plus élevées.";
$LOCA["fr"]["LONG_212"] = "Les scientifiques ont découvert une méthode pour transmettre de l'énergie électrique à la colonie en utilisant des satellites spécialement conçus en orbite géosynchrone. Les satellites solaires recueillent l'énergie solaire et la transmettent à une station au sol en utilisant une technologie laser avancée. L'efficacité d'un satellite solaire dépend de la force du rayonnement solaire qu'il reçoit. En principe, la production d'énergie sur les orbites plus proches du soleil est plus grande que pour les planètes sur des orbites éloignées du soleil.<br/>
Grâce à leur bon rapport coût/performance, les satellites solaires peuvent résoudre de nombreux problèmes d'énergie. Mais attention : les satellites solaires peuvent être facilement détruits au combat.";
$LOCA["fr"]["LONG_213"] = "Le destructeur est le résultat d'années de travail et de développement. Avec le développement des morts noires, il a été décidé qu'une classe de vaisseaux était nécessaire pour se défendre contre une arme aussi massive. Grâce à ses capteurs de guidage améliorés, ses canons à ions multi-phalanges, ses canons de Gauss et ses lanceurs de plasma, le destructeur s'est avéré être l'un des vaisseaux les plus redoutables jamais créés.<br/>
Parce que le destructeur est très grand, sa manœuvrabilité est sévèrement limitée, ce qui en fait davantage une station de combat qu'un vaisseau de combat. Le manque de manœuvrabilité est compensé par sa puissance de feu pure, mais il coûte également des quantités importantes de deutérium à construire et à exploiter.";
$LOCA["fr"]["LONG_214"] = "La mort noire est le vaisseau le plus puissant jamais créé. Ce vaisseau de la taille d'une lune est le seul vaisseau qui peut être vu à l'œil nu depuis le sol. Au moment où vous le repérez, malheureusement, il est trop tard pour faire quoi que ce soit.<br/>
Armé d'un gigantesque canon à gravitons, le système d'armes le plus avancé jamais créé dans l'univers, ce vaisseau massif a non seulement la capacité de détruire des flottes et des défenses entières, mais aussi la capacité de détruire des lunes entières. Seuls les empires les plus avancés ont la capacité de construire un vaisseau de cette taille mammouth.";
$LOCA["fr"]["LONG_215"] = "Ce vaisseau est l'un des vaisseaux de combat les plus avancés jamais développés, et il est particulièrement redoutable lorsqu'il s'agit de détruire des flottes attaquantes. Avec ses canons laser améliorés à bord et son moteur hyperspatial avancé, le croiseur de bataille est une force sérieuse à affronter lors de toute attaque. En raison de la conception du vaisseau et de son système d'armes volumineux, les cales de chargement ont dû être réduites, mais cela est compensé par la consommation de carburant réduite.";

$LOCA["fr"]["LONG_401"] = "Votre première ligne de défense de base. Ce sont de simples installations de lancement au sol qui tirent des missiles à ogive conventionnelle sur les cibles ennemies attaquantes. Comme elles sont peu coûteuses à construire et qu'aucune recherche n'est requise, elles conviennent bien pour défendre les raids, mais perdent de leur efficacité pour défendre contre des attaques à plus grande échelle. Une fois que vous commencez la construction de systèmes d'armes défensives plus avancés, les lanceurs de missiles deviennent de simples appâts qui permettent à vos armes plus destructrices d'infliger de plus grands dégâts pendant une plus longue période.";
$LOCA["fr"]["LONG_402"] = "À mesure que la technologie se développait et que des vaisseaux plus sophistiqués étaient créés, il a été déterminé qu'une ligne de défense plus solide était nécessaire pour contrer les attaques. À mesure que la technologie laser progressait, une nouvelle arme a été conçue pour fournir le niveau de défense suivant. Les lasers légers sont de simples armes au sol qui utilisent des systèmes de ciblage spéciaux pour suivre l'ennemi et tirer un laser de haute intensité conçu pour traverser la coque de la cible. Afin de rester rentables, ils ont été équipés d'un système de bouclier amélioré, mais l'intégrité structurelle est la même que celle du lanceur de missiles.";
$LOCA["fr"]["LONG_403"] = "Le laser lourd est une version pratique et améliorée du laser léger. Étant plus équilibré que le laser léger grâce à une composition d'alliage améliorée, il utilise des faisceaux plus puissants et plus denses, ainsi que de meilleurs systèmes de ciblage embarqués.";
$LOCA["fr"]["LONG_404"] = "Pendant longtemps, les armes à projectiles ont été considérées comme antiques face à la technologie thermonucléaire et énergétique moderne et au développement de l'hyperpropulsion et des armures améliorées. Jusqu'à ce que la technologie énergétique exacte qui l'avait autrefois vieillie l'aide à retrouver sa position établie.<br/>
Un canon de Gauss est une grande version de l'accélérateur de particules. Des projectiles extrêmement lourds sont accélérés avec une force électromagnétique énorme et possèdent des vitesses à la bouche qui font brûler la poussière entourant le projectile dans les cieux. Cette arme est si puissante lorsqu'elle est tirée qu'elle crée un bang sonique. L'armure et les boucliers modernes peuvent à peine résister à la force ; souvent, la cible est complètement transpercée par la puissance du projectile. Les structures défensives se désactivent dès qu'elles ont été trop gravement endommagées.";
$LOCA["fr"]["LONG_405"] = "Un canon à ions est une arme qui tire des faisceaux d'ions (particules chargées positivement ou négativement). Le canon à ions est en fait un type de canon à particules ; seules les particules utilisées sont ionisées. En raison de leurs charges électriques, ils ont également le potentiel de désactiver les dispositifs électroniques, et tout autre chose qui possède une source d'énergie électrique ou similaire, en utilisant un phénomène connu sous le nom d'impulsion électromagnétique (effet EMP). Grâce au système de bouclier hautement amélioré du canon, ce canon fournit une protection améliorée pour vos armes défensives plus grandes et plus destructrices.";
$LOCA["fr"]["LONG_406"] = "L'un des systèmes d'armes défensives les plus avancés jamais développés, le lanceur de plasma utilise une grande cellule de combustible à réacteur nucléaire pour alimenter un accélérateur électromagnétique qui tire une impulsion, ou tore, de plasma. Pendant le fonctionnement, le lanceur de plasma verrouille d'abord une cible et commence le processus de tir. Une sphère de plasma est créée dans le cœur du lanceur en surchauffant et en comprimant des gaz, en les dépouillant de leurs ions. Une fois le gaz surchauffé, comprimé et qu'une sphère de plasma est créée, elle est ensuite chargée dans l'accélérateur électromagnétique qui est alimenté en énergie. Une fois complètement alimenté, l'accélérateur est activé, ce qui entraîne le lancement de la sphère de plasma à une vitesse extrêmement élevée vers la cible prévue. Du point de vue de la cible, la boule de plasma bleuâtre qui approche est impressionnante, mais une fois qu'elle frappe, elle provoque une destruction instantanée.";
$LOCA["fr"]["LONG_407"] = "La colonisation de nouveaux mondes a apporté un nouveau danger : les débris spatiaux. Un gros astéroïde pouvait facilement anéantir le monde et tous ses habitants. Les progrès de la technologie des boucliers ont fourni aux scientifiques un moyen de développer un bouclier pour protéger une planète entière non seulement des débris spatiaux mais, comme on l'a appris, d'une attaque ennemie. En créant un grand champ électromagnétique autour de la planète, les débris spatiaux qui auraient normalement détruit la planète étaient déviés, et les attaques des empires ennemis étaient déjouées. Les premiers générateurs étaient grands et le bouclier fournissait une protection modérée, mais il a été découvert plus tard que les petits boucliers n'offraient pas la protection contre les attaques à plus grande échelle. Le petit dôme de bouclier était le prélude à un système de bouclier planétaire plus solide et plus avancé à venir.";
$LOCA["fr"]["LONG_408"] = "Le grand dôme de bouclier est la prochaine étape dans l'avancement des boucliers planétaires ; c'est le résultat d'années de travail d'amélioration du petit dôme de bouclier. Conçu pour résister à un barrage plus important de tirs ennemis en fournissant un champ électromagnétique plus énergisé, les grands dômes fournissent une période de protection plus longue avant de s'effondrer.";
$LOCA["fr"]["LONG_502"] = "Les missiles anti-balistiques (MAB) sont votre seule ligne de défense lorsque votre planète ou votre lune est attaquée par des missiles interplanétaires (MIP). Lorsqu'un lancement de MIP est détecté, ces missiles s'arment automatiquement, traitent un code de lancement dans leurs ordinateurs de vol, ciblent le MIP entrant et se lancent pour l'intercepter. Pendant le vol, le MIP cible est constamment suivi et des corrections de cap sont appliquées jusqu'à ce que le MAB atteigne la cible et détruise le MIP attaquant. Chaque MAB détruit un MIP entrant.";
$LOCA["fr"]["LONG_503"] = "Les missiles interplanétaires (MIP) sont votre arme offensive pour détruire les défenses de votre cible. Utilisant une technologie de suivi de pointe, chaque missile cible un certain nombre de défenses à détruire. Équipés d'une bombe à antimatière, ils délivrent une force destructrice si sévère que les boucliers et les défenses détruits ne peuvent pas être réparés. La seule façon de contrer ces missiles est d'utiliser des MAB.";

?>
