<?php

// Erweiterte Beschreibung der Objekte.

$LOCA["de"]["LONG_1"] = "Hauptrohstoff für den Bau tragender Strukturen von Gebäuden und Schiffen. Metall ist zwar der günstigste Rohstoff und braucht zur Herstellung am wenigsten Energie, dafür wird davon auch mehr benötigt als von anderen. Je weiter die Minen ausgebaut sind, desto tiefer können sie vordringen. Da bei den meisten Planeten die besten Metallerze in großer Tiefe lagern, steigt durch die Erweiterung der Minen auch die Produktion. Gleichzeitig muss für eine größere Metallmine mehr Energie zur Verfügung gestellt werden.";
$LOCA["de"]["LONG_2"] = "Die Kristallmine liefert den Hauptrohstoff für elektronische Bauteile und Legierungen. Sie verbraucht beim Abbau etwa anderthalb mal so viel Energie wie die Metallmine, was Kristall entsprechend wertvoller macht. Fast alle Schiffe und alle Gebäude benötigen Kristall. Die meisten für den Raumschiffbau benötigten Kristalle sind jedoch sehr selten und wie Metall in größeren Mengen erst in einer entsprechenden Tiefe zu finden. Ein Ausbau der Mine bis in tiefere Schichten erhöht deshalb auch die Menge an geförderten Kristallen.";
$LOCA["de"]["LONG_3"] = "Deuterium ist schwerer Wasserstoff, der vor allem in der Tiefe des Meeres lagert. Ein Synthetisierer hat deshalb eine den Minen ähnliche Funktionsweise. Der Ausbau des Synthetisierers sorgt ebenfalls für die bessere Erschließung dieser Deuterium-Tiefenlagerstätten.
Deuterium wird als Treibstoff für die Schiffe und fast alle Forschungen benötigt. Zudem wird er eingesetzt, um die Galaxie zu betrachten oder Scans mit der Sensorphalanx durchzuführen.";
$LOCA["de"]["LONG_4"] = "Um die Energie zur Versorgung der Minen und Synthetisierern zu gewährleisten, sind riesige Solarkraftwerkanlagen vonnöten. Je größer die Anlagen ausgebaut sind, desto mehr Fläche wird mit photovoltaischen Zellen bedeckt, welche Lichtenergie in elektrische Energie umwandeln. Solarkraftwerke bilden den Grundstock der planetaren Energieversorgung.";
$LOCA["de"]["LONG_12"] = "In Fusionskraftwerken werden unter enormem Druck und mit hoher Temperatur je zwei Wasserstoffatome zu einem Heliumatom fusioniert. Dabei werden ungeheure Mengen Energie in Form von Strahlung freigesetzt.<br/>
Je größer der Fusionsreaktor ist, desto kompliziertere Anschlussfusionen lassen sich herstellen, und der Reaktor erzeugt mehr Energie. Die Energieausbeute kann zudem durch Forschungen im Bereich der Energietechnik gesteigert werden.<br/>
Die Energieproduktion des Fusionskraftwerkes bemisst sich somit nach folgender Formel:<br/>
30 * [Stufe Fusionskraftwerk] * (1,05 + [Stufe Energietechnik] * 0,01) ^ [Stufe Fusionskraftwerk]";
$LOCA["de"]["LONG_14"] = "Roboterfabriken stellen einfache Arbeitskräfte zur Verfügung, die beim Bau der planetaren Infrastruktur eingesetzt werden können. Jede Stufe erhöht damit die Geschwindigkeit des Ausbaus von Gebäuden.";
$LOCA["de"]["LONG_15"] = "Die Nanitenfabrik ist die Krönung der Robotertechnik. Naniten sind nanometergroße mechanische Einheiten, die sich vernetzen und in Sekundenbruchteilen zu präzisen Werkzeugen zusammensetzen können. Die Nanitenfabrik halbiert die Bauzeit von Gebäuden, Schiffen und Verteidigungsanlagen pro Stufe.";
$LOCA["de"]["LONG_21"] = "Die planetare Werft ist dein Grundstein für den intergalaktischen Feldzug. Dort werden Schiffe gebaut, mit denen du ferne Welten erobern kannst, sowie Verteidigungsanlagen, die deinen Planeten vor einem Angriff schützen. Mit der Größe der Werft steigt auch ihre Geschwindigkeit und die Kapazität, um größere Schiffe oder Verteidigungsanlagen zu bauen.";
$LOCA["de"]["LONG_22"] = "Riesige Lagerstätte für abgebaute Metallerze. Je größer der Speicher, desto mehr Metall kann darin gelagert werden. Ist das Lager voll, wird kein Metall mehr abgebaut.";
$LOCA["de"]["LONG_23"] = "Das noch unbearbeitete Kristall wird in diesen riesigen Lagerhallen zwischengespeichert. Je größer das Lager, desto mehr Kristall kann in ihm eingelagert werden. Sind die Kristalllager voll, wird kein weiteres Kristall abgebaut.";
$LOCA["de"]["LONG_24"] = "Riesige Tanks zur Lagerung des neu gewonnenen Deuteriums. Diese Lager findet man meist in der Nähe von Raumhäfen. Je größer sie sind, desto mehr kann in ihnen gelagert werden. Sind sie gefüllt, wird kein Deuterium mehr abgebaut.";
$LOCA["de"]["LONG_31"] = "In einem Forschungslabor arbeiten Wissenschaftler an neuen Technologien, die dir erlauben, deine Basis auszubauen und ferne Planeten zu erobern. Je größer dieses Labor ist, desto mehr Forscher finden Platz, und die Arbeit geht schneller voran. Zudem erlauben es dir höhere Ausbaustufen, in bisher unbekannte Wissenschaftsgebiete vorzudringen. Wird an einer neuen Entdeckung gearbeitet, kommen alle Forscher deines Imperiums, um das neue Wissen zu erlernen und in ihrer Heimat zu verbreiten. So kann die Technologie überall eingesetzt werden. Für die Dauer der Entwicklung stehen aber auf allen anderen Planeten die Zentrifugen still.";
$LOCA["de"]["LONG_33"] = "Mit zunehmendem Ausbau der Planeten wurde auch der Lebensraum auf der Kolonie immer begrenzter. Traditionelle Methoden wie Hoch- und Tiefbau erwiesen sich zunehmend als unzureichend. Eine kleine Gruppe von Hochenergiephysikern und Nanotechnikern fand schließlich die Lösung: das Terraforming.<br/>
Unter dem Aufwand riesiger Energiemengen kann der Terraformer ganze Landstriche oder gar Kontinente urbar machen. In diesem Gebäude werden fortwährend eigens dafür konstruierte Naniten produziert, die für eine konstante Qualität des Bodens sorgen.<br/>
Pro Terraformerlevel können 5 Felder bebaut werden. Hierbei belegt jede Stufe des Terraformers selbst auch ein Feld. Alle 2 Terraformerlevel bekommt man 1 Bonusfeld gut geschrieben.<br/>
Einmal gebaut, kann der Terraformer nicht wieder abgerissen werden.";
$LOCA["de"]["LONG_34"] = "Im Allianzdepot lassen sich befreundete Flotten, die bei der Verteidigung helfen und im Orbit stehen, mit Treibstoff versorgen. Für jedes Ausbaulevel des Allianzdepots kann eine bestimmte Menge Deuterium pro Stunde an die zu versorgenden Flotten im Orbit geschickt werden.";
$LOCA["de"]["LONG_41"] = "Ein Mond verfügt über keinerlei Atmosphäre, deshalb muss vor der Besiedlung eine Mondbasis errichtet werden. Diese sorgt für die nötige Atemluft, Gravitation und Wärme. Je höher die Ausbaustufe der Mondbasis ist, desto größer ist die Fläche, die mit einer Biosphäre versorgt wird. Pro Mondbasislevel können 3 Felder bebaut werden. Hierbei belegt jede Stufe der Mondbasis selbst auch ein Feld.<br/>
Einmal gebaut, kann die Mondbasis nicht wieder abgerissen werden.";
$LOCA["de"]["LONG_42"] = "Hochauflösende Sensoren scannen das vollständige Frequenzspektrum aller auf die Phalanx auftreffenden Strahlung. Hochleistungscomputer kombinieren winzige Energieschwankungen und gewinnen so Informationen über Schiffsbewegungen auf entfernten Planeten. Für den Scan muss Energie in Form von Deuterium (5.000) auf dem Mond bereitgestellt werden. Man scannt, indem man vom Mond aus ins Galaxiemenü wechselt und auf einen feindlichen Planeten in Sensorenreichweite (Phalanxstufe)^2 - 1 klickt.";
$LOCA["de"]["LONG_43"] = "Sprungtore sind riesige Transmitter, die selbst große Flotten ohne Zeitverlust durch das Universum schicken können. Diese Transmitter verbrauchen kein Deuterium. Allerdings wird bei einem Sprung sehr große Hitze erzeugt. Sprungtore brauchen einige Minuten, um abzukühlen und einen weiteren Sprung durchführen zu können. Auch können keine Ressourcen mit versendet werden. Mit jeder Ausbaustufe kann die Cooldown-Zeit des Sprungtores verkürzt werden.";
$LOCA["de"]["LONG_44"] = "Raketensilos dienen zum Einlagern von Raketen. Pro ausgebauter Stufe kann man fünf Interplanetar- oder zehn Abfangraketen einlagern. Eine Interplanetarrakete benötigt dabei so viel Platz wie zwei Abfangraketen. Unterschiedliche Raketentypen können beliebig kombiniert werden.";

$LOCA["de"]["LONG_106"] = "Die Spionagetechnik ist in erster Linie die Weiterentwicklung von Sensortechnologie. Je höher diese Technik entwickelt ist, umso mehr Informationen stehen dem Nutzer über Vorgänge in seiner Umgebung zur Verfügung.
Für Sonden ist die Differenz des eigenen und des gegnerischen Spionagelevels entscheidend. Je weiter die eigene Spionagetechnik erforscht ist, desto mehr Informationen enthält der Bericht und desto kleiner ist die Chance, dass eine Spionageaktion entdeckt wird. Je mehr Sonden in einer Mission geschickt werden, desto mehr Details können sie vom Zielplaneten übermitteln. Gleichzeitig steigt aber auch die Gefahr der Entdeckung.<br/>
Die Spionagetechnik verbessert ebenfalls die Ortung fremder Flotten. Dabei ist nur der eigene Spionagelevel entscheidend. Ab Level 2 wird zusätzlich zur reinen Angriffsmeldung auch die Gesamtanzahl der angreifenden Schiffe angezeigt, ab Level 4 die Art der angreifenden Schiffe sowie die Gesamtanzahl und ab Level 8 die genaue Anzahl der verschiedenen Schiffstypen.
Für einen bevorstehenden Angriff ist diese Technik unverzichtbar, da sie Auskunft darüber gibt, ob das Opfer eine Flotte und/oder Verteidigung besitzt oder nicht. Deshalb sollte diese Technik schon sehr früh erforscht werden.";
$LOCA["de"]["LONG_108"] = "Die Erweiterung der Computerkapazitäten wird im Gebiet der Computertechnik erforscht. Immer leistungsfähigere und effizientere Computersysteme werden entwickelt. Die Rechenleistung steigt und die Geschwindigkeit, mit der Rechenprozesse ablaufen, wird ebenfalls erhöht. Somit lassen sich immer mehr Flotten gleichzeitig verwalten. Jede Stufe der Computertechnik erhöht dabei die maximale Flottenanzahl um eins. So lassen sich mehr Angriffe und mehr Handel durchführen, und die Profite oder erbeuteten Rohstoffe steigen. Deshalb sollte die Computertechnik über das gesamte Spiel hinweg ausgebaut werden.";
$LOCA["de"]["LONG_109"] = "In der Waffentechnik werden vor allem schon bestehende Waffensysteme weiterentwickelt. Der Schwerpunkt liegt dabei darin, die vorhandenen Systeme mit mehr Energie auszustatten und diese punktgenauer zu kanalisieren.
Dadurch werden die Waffensysteme effizienter und richten mehr Schaden an. Jede Stufe der Waffentechnik erhöht die Waffenstärke der Einheiten um 10% des Grundwertes.<br/>
Die Waffentechnik ist wichtig, um später die eigenen Einheiten konkurrenzfähig zu halten. Deshalb sollte sie das ganze Spiel hindurch weiterentwickelt werden.";
$LOCA["de"]["LONG_110"] = "Mit der Schildtechnik wird nach neuen Möglichkeiten geforscht, die Schilde mit mehr Energie zu versorgen und sie so effizienter und belastbarer zu machen. Dadurch steigt mit jeder erforschten Stufe die Effizienz der Schilde um 10% des Grundwertes.";
$LOCA["de"]["LONG_111"] = "Spezielle Legierungen machen die Panzerung der Raumschiffe immer besser. Ist einmal eine sehr widerstandsfähige Legierung gefunden, wird durch spezielle Strahlungen die molekulare Struktur des Raumschiffes verändert und auf den Stand der besten derzeit erforschten Legierung gebracht. Die Wirksamkeit der Panzerung kann so pro Stufe um 10% des Grundwertes gesteigert werden.";
$LOCA["de"]["LONG_113"] = "Die Energietechnik beschäftigt sich mit der Weiterentwicklung von Leitsystemen und mit Speicherung, welche für viele neue Technologien benötigt wird.";
$LOCA["de"]["LONG_114"] = "Durch die Nutzung der vierten und fünften Dimension ist es nun möglich, einen neuartigen Antrieb zu erforschen, der sparsamer und leistungsfähiger ist. Jede Stufe dieser Technologie erhöht die Ladekapazität deiner Schiffe um 5% des Grundwertes.";
$LOCA["de"]["LONG_115"] = "Verbrennungstriebwerke basieren auf dem uralten Rückstoßprinzip. Materie wird hoch erhitzt und erzeugt so einen Schub, der das Schiff antreibt. Der Wirkungsgrad dieser Triebwerke ist eher gering, aber sie sind billig und zuverlässig und benötigen kaum Wartung. Außerdem verbrauchen sie weniger Raum und werden deshalb gerade auf kleineren Schiffen eingesetzt. Da Verbrennungstriebwerke die Grundlage jeder Raumfahrt sind, sollten sie so früh wie möglich erforscht werden. Die Weiterentwicklung dieser Triebwerke macht folgende Schiffe um 10% des Grundwertes pro Stufe schneller: Kleine und große Transporter, leichte Jäger, Recycler und Spionagesonden.";
$LOCA["de"]["LONG_117"] = "Das Impulstriebwerk basiert auf dem Rückstoßprinzip, wobei die Strahlmasse zum Großteil als Abfallprodukt der zur Energiegewinnung verwendeten Kernfusion entsteht. Zusätzlich kann weitere Masse eingespritzt werden. Die Weiterentwicklung dieser Triebwerke macht folgende Schiffe um 20% des Grundwertes pro Stufe schneller: Bomber, Kreuzer, schwere Jäger und Kolonieschiffe. Außerdem wird der kleine Transporter mit Impulstriebwerk ausgestattet, sobald die Forschung Stufe 5 erreicht.<br/>
Interplanetarraketen können pro Stufe weiter fliegen.";
$LOCA["de"]["LONG_118"] = "In unmittelbarer Umgebung des Schiffes wird der Raum gekrümmt, so dass sich weite Strecken sehr schnell zurücklegen lassen. Je höher der Hyperraumantrieb entwickelt ist, desto stärker wird die Krümmung des Raums, wodurch sich pro Stufe die Geschwindigkeit der Schiffe, die damit ausgestattet sind (Schlachtkreuzer, Schlachtschiffe, Zerstörer, Todessterne, Pathfinder und Reaper) um 30% erhöht. Außerdem wird der Bomber mit Hyperraumantrieb ausgestattet, sobald die Forschung Stufe 8 erreicht.";
$LOCA["de"]["LONG_120"] = "Laser (Lichtverstärkung durch induzierte Strahlungsemission) erzeugen einen intensiven, energiereichen Strahl von kohärentem Licht. Diese Geräte finden in allen möglichen Bereichen ihre Anwendung, von optischen Computern bis hin zu schweren Laserwaffen, die mühelos durch Raumschiffpanzerungen schneiden. Die Lasertechnik bildet einen wichtigen Grundstein für die Erforschung weiterer Waffentechnologien.";
$LOCA["de"]["LONG_121"] = "Ionen können zu einem tödlichen Richtstrahl konzentriert und beschleunigt werden. Diese Strahlen können beträchtlichen Schaden anrichten. Unsere Wissenschaftler haben eine Technik entwickelt, die die Abrisskosten für Gebäude und Anlagen deutlich senkt.";
$LOCA["de"]["LONG_122"] = "Eine Weiterentwicklung der Ionentechnik, die nicht Ionen beschleunigt, sondern hochenergetisches Plasma, das beim Auftreffen auf ein Objekt verheerenden Schaden anrichten kann.";
$LOCA["de"]["LONG_123"] = "Nachdem die Forschungen immer komplexer wurden, entwickelten die<br/>
Wissenschaftler eine revolutionäre Methode, die einzelnen Labore<br/>
miteinander zu vernetzen: Das Intergalaktische Forschungsnetzwerk!<br/>
Über dieses Netzwerk werden die Zentralrechner der einzelnen<br/>
Forschungsstationen direkt miteinander verbunden, wodurch die Forschungen beschleunigt werden.<br/>
Pro erforschtes Level wird ein Forschungslabor vernetzt. Dabei werden<br/>
immer die Labore der höchsten Stufe dazugeschaltet.<br/>
Das vernetzte Labor muss ausreichend ausgebaut sein, um die anstehende<br/>
Forschung selbständig durchführen zu können. Die Ausbaustufen aller<br/>
beteiligten Labore werden im intergalaktischen Forschungsnetzwerk<br/>
zusammengezählt.";
$LOCA["de"]["LONG_124"] = "Die Expeditionstechnologie umfasst verschiedene Scantechnologien und ermöglicht es, Schiffe verschiedener Klassen mit einem Forschungsmodul auszustatten. Es enthält eine Datenbank, ein kleines mobiles Labor sowie verschiedene Biozellen und Probengefäße.  Zur Sicherheit des Schiffes bei der Erkundung gefährlicher Objekte ist das Forschungsmodul mit einer autonomen Energieversorgung und einem Energiefeldgenerator ausgestattet, der das Forschungsmodul in Extremsituationen mit einem starken Energiefeld umgeben kann.";
$LOCA["de"]["LONG_199"] = "Ein Graviton ist ein Partikel, das keine Masse und keine Ladung besitzt. Es bestimmt die Gravitationskraft. Durch Abschuss einer konzentrierten Ladung von Gravitonen kann ein künstliches Gravitationsfeld errichtet werden. Es zieht - ähnlich einem schwarzen Loch - Masse in sich hinein. So kann es Schiffe und sogar ganze Monde vernichten. Um eine ausreichende Menge Gravitonen herzustellen, werden ungeheure Mengen an Energie benötigt. Ohne Gravitonforschung ist es nicht möglich, einen zerstörerischen Todesstern zu konstruieren.";

$LOCA["de"]["LONG_202"] = "Transporter haben etwa die Größe von Jägern, verzichten allerdings auf leistungsfähige Antriebe und Bordwaffen zugunsten ihres Frachtraums. In Schlachten sollte ein Transporter deshalb nur dann geschickt werden, wenn er von kampfbereiten Schiffen unterstützt wird.<br/>
Sobald das Impulstriebwerk auf Stufe 5 erforscht ist, fliegt der kleine Transporter mit erhöhter Grundgeschwindigkeit und wird mit dem Impulstriebwerk ausgestattet.";
$LOCA["de"]["LONG_203"] = "Der große Transporter dient durch sein hochentwickeltes Verbrennungstriebwerk als schneller Ressourcenlieferant zwischen den Planeten. Er ist jedoch nur mit wenigen Hilfswaffen ausgerüstet und besitzt kaum Panzerung. In den Kampf geschickt werden sollte er deshalb nur zur Erbeutung von Ressourcen in Begleitung von bewaffneten Schiffen.";
$LOCA["de"]["LONG_204"] = "Der leichte Jäger ist ein wendiges Schiff, das in dieser Form auf fast jedem Planeten eingesetzt wird. Seine Kosten sind gering, Schildstärke und Ladekapazität allerdings ebenfalls.";
$LOCA["de"]["LONG_205"] = "Bei der Weiterentwicklung des leichten Jägers kamen die Forscher an einen Punkt, an dem der konventionelle Antrieb nicht mehr ausreichte. Um das neue Schiff optimal anzutreiben, wurde zum ersten Mal der Impulsantrieb eingesetzt. Das erhöhte zwar die Kosten, eröffnete aber auch neue Möglichkeiten. Durch den Einsatz dieses Antriebs blieb mehr Energie für Waffen und Schilde übrig. Zudem wurden für diesen neuen Typ Jäger auch qualitativ hochwertigere Materialien verwendet. Dies führte zu einer verbesserten strukturellen Integrität und einer höheren Feuerkraft. So ist der schwere Jäger im Kampf eine sehr viel größere Bedrohung als sein leichtes Pendant. Diese Änderungen machen ihn zu einem Quantensprung in der Schiffstechnologie und bilden gleichzeitig die Basis für den Bau von Kreuzern.";
$LOCA["de"]["LONG_206"] = "Mit der Entwicklung der schweren Laser und der Ionenkanonen kamen die Jäger immer mehr in Bedrängnis. Trotz vieler Modifikationen konnten Waffenstärke und Panzerung nicht ausreichend verbessert werden, um diesen Verteidigungsgeschützen wirksam begegnen zu können.
Deshalb entschied man sich, eine neue Schiffsklasse zu konstruieren, die mehr Panzerung und mehr Feuerkraft in sich vereint: Kreuzer sind fast dreimal so stark gepanzert wie schwere Jäger und verfügen über mehr als die doppelte Schusskraft. Zudem sind sie sehr schnell. Gegen mittelstarke Verteidigung gibt es kaum eine bessere Waffe.";
$LOCA["de"]["LONG_207"] = "Schlachtschiffe sind das Rückgrat einer Flotte. Ihre schweren Geschütze und die hohe Geschwindigkeit machen sie zu ernst zu nehmenden Gegnern und der Frachtraum ist großzügig genug bemessen, um genügend Beute heimzubringen.";
$LOCA["de"]["LONG_208"] = "Mit diesem Schiff kannst du neue Planeten erobern - unerlässlich für ein aufstrebendes Imperium! Wenn das Schiff auf einem neuen, noch unentdeckten Planeten landet, wird es zur Basis umfunktioniert. Es stellt genügend Material bereit, um mit der Erschließung der neuen Welt zu beginnen. Jedes Reich, einschließlich des Hauptplaneten, kann bis zu 9 Planeten kolonisieren.";
$LOCA["de"]["LONG_209"] = "Die Weltraumgefechte nahmen immer größere Ausmaße an. Tausende Schiffe wurden zerstört und die Rohstoffe ihrer Überreste schienen für immer in den Trümmerfeldern verschollen. Normale Transporter kamen nicht nah genug an diese Felder heran, ohne durch Trümmerteile größeren Schaden zu erleiden.
Mit einer neuen Entwicklung bei der Schildtechnologie konnte dieses Problem effizient beseitigt werden. Es entstand eine neue Schiffsklasse, die dem Transporter ähnelt: der Recycler. Mit dessen Hilfe können die scheinbar verlorenen Ressourcen nun eingesammelt und somit verwertet werden. Die Trümmerteile stellten aufgrund der neuen Schilde auch keine Gefahr mehr dar.";
$LOCA["de"]["LONG_210"] = "Spionagesonden sind kleine Drohnen, die über weite Entfernungen Daten zu Flotten und Planeten liefern. Sie verfügen über ein Hochleistungstriebwerk, das sie sehr weite Strecken in wenigen Sekunden zurücklegen lässt. Sie nutzen die Umlaufbahn eines Planeten, um Daten zu sammeln und gleichzeitig wieder Kurs auf die Heimat zu nehmen. Während ihrer Zeit im Orbit sind sie vom Feind relativ leicht zu entdecken. Da sie über keinerlei Panzerung, Schilde oder Waffen verfügen, sind sie einfache Opfer für planetare Verteidigungsanlagen.";
$LOCA["de"]["LONG_211"] = "Der Bomber wurde entwickelt, um die Verteidigung eines Planeten zu zerstören. Mithilfe einer lasergesteuerten Zielvorrichtung wirft er zielgenau Plasmabomben auf die Planetenoberfläche und richtet so einen verheerenden Schaden bei Verteidigungsanlagen an.<br/>
Der Bomber kann mit einem Hyperraumantrieb ausgestattet werden, sobald die entsprechende Forschung Stufe 8 erreicht hat. Damit erhöht sich seine Geschwindigkeit deutlich.";
$LOCA["de"]["LONG_212"] = "Solarsatelliten werden in eine geostationäre Umlaufbahn um einen Planeten geschossen. Sie bündeln Sonnenenergie und lenken diese auf ein Spiegelsystem am Boden. Die Effizienz der Solarsatelliten hängt von der Stärke der Sonneneinstrahlung ab. Grundsätzlich ist die Energieausbeute auf sonnennahen Planeten größer als bei solchen, die weiter entfernt von der Sonne sind. Durch ihr gutes Preis-Leistungs-Verhältnis lösen Solarsatelliten die Energieprobleme vieler Welten. Aber Vorsicht: Solarsatelliten können im Kampf zerstört werden.";
$LOCA["de"]["LONG_213"] = "Der Zerstörer ist der König unter den Kriegsschiffen. Seine Multiphalanx-Ionen-, Plasma- und Gaußgeschütztürme haben durch ihre verbesserte Peilsensorik besonders leichtes Spiel gegen einfache Technologie wie leichte Laser. Aufgrund seiner Größe ist seine Manövrierfähigkeit stark eingeschränkt, wodurch er in der Schlacht eher einer Kampfstation gleicht als einem Schiff. Um ihn in Bewegung zu setzen, ist eine Menge Deuterium nötig.";
$LOCA["de"]["LONG_214"] = "Mit seiner riesigen Gravitonkanone verbreitet der Todesstern Furcht und Schrecken in der gesamten Galaxis. Diese Kanone ist in der Lage, selbst große Schiffe wie Zerstörer oder sogar Monde mühelos zu vernichten. Die ungeheure Menge an Energie, die er dafür benötigt, wird durch Generatoren erzeugt, die für einen Großteil der Masse dieses beinahe mondgroßen Ungetüms sorgen.";
$LOCA["de"]["LONG_215"] = "Dieses Schiff wurde ganz auf den Kampf gegen größere Flottenverbände ausgelegt.<br/>
Mit seinen hochentwickelten Lasergeschützen ist es in der Lage, eine große Zahl angreifender Schiffe gleichzeitig zu bekämpfen.<br/>
Durch seine schlanke Bauform und die starke Bewaffnung ist die Ladekapazität begrenzt, dafür ist der Hyperraumantrieb verbrauchsarm.";

$LOCA["de"]["LONG_401"] = "Der Raketenwerfer ist eine einfache und kostengünstige Verteidigungsmöglichkeit. Da er nur eine Weiterentwicklung gewöhnlicher ballistischer Feuerwaffen ist, benötigt er keine weitere Forschung. Seine geringen Herstellungskosten rechtfertigen seinen Einsatz gegen kleinere Flotten. Allerdings verliert er durch den Anstieg der Flottenstärken und immer größere Raumschiffe langsam an Relevanz. Später wird er nur noch als Schussfang hinter großen Geschützen eingesetzt. Verteidigungsanlagen deaktivieren sich selbst, sobald sie zu stark beschädigt sind.";
$LOCA["de"]["LONG_402"] = "Mit den Fortschritten der Raumschifftechnologie wuchs auch der Bedarf an angemessenen Verteidigungsanlagen. So wurde der leichte Laser entwickelt. Durch den konzentrierten Beschuss eines Ziels mit Photonen konnte wesentlich mehr Schaden erzielt werden als mit gewöhnlichen ballistischen Waffen. Um der größeren Feuerkraft der neuen Schiffstypen widerstehen zu können, wurde er außerdem mit verbesserten Schilden ausgestattet. Um die Produktionskosten dennoch gering zu halten, wurde die Struktur nicht weiter verstärkt. Der leichte Laser besitzt das beste Preis-Leistungs-Verhältnis und ist dadurch auch für weiter fortgeschrittene Zivilisationen interessant. Verteidigungsanlagen deaktivieren sich, sobald sie zu stark beschädigt sind.";
$LOCA["de"]["LONG_403"] = "Der schwere Laser ist die konsequente Weiterentwicklung des leichten Lasers. Die Struktur wurde verstärkt und mit neuen Materialien verbessert. Die Hülle konnte so wesentlich widerstandsfähiger gemacht werden. Gleichzeitig wurden auch das Energiesystem und der Zielcomputer verbessert, so dass ein schwerer Laser wesentlich mehr Energie auf ein Ziel konzentrieren kann. Verteidigungsanlagen deaktivieren sich, sobald sie zu stark beschädigt sind.";
$LOCA["de"]["LONG_404"] = "Projektilwaffen galten lange Zeit als antiquiert im Schatten von moderner Kernfusions- und Energietechnik, der Entwicklung des Hyperraumantriebs und immer besserer Panzerungen. Bis eben genau die Energietechnik, die sie einst verdrängt hatte, ihnen wieder zu ihrem angestammten Platz verhalf.
Eine Gaußkanone ist eine große Variante eines Teilchenbeschleunigers. Tonnenschwere Geschosse werden unter gigantischem elektrischem Aufwand magnetisch beschleunigt und haben Mündungsgeschwindigkeiten, die die Schmutzteilchen in der Luft um das Geschoss verbrennen lassen. Der gewaltige Rückstoß lässt die Erde rund um die Kanone erbeben. Dieser Durchschlagskraft können auch moderne Panzerungen und Schilde schwer widerstehen, oft wird das Ziel komplett von der Wucht des Geschosses durchschlagen. Verteidigungsanlagen deaktivieren sich, sobald sie zu stark beschädigt sind.";
$LOCA["de"]["LONG_405"] = "Schon seit dem 20. Jahrhundert der Erdzeitrechnung ist die Technik des Elektromagnetischen Pulses (EMP) bekannt. Ein EMP induziert Spannungen, die auf Schaltkreisen in der Nähe Störungen bis hin zu Kurzschlüssen auslösen können.<br/>
Damals wurden EMP-Waffen vor allem auf Basis von Raketen oder Bomben eingesetzt oder die Pulse waren die Nebenwirkungen von Nuklearwaffen.<br/>
Seit dieser Zeit wurde der EMP stark weiterentwickelt, da er das Potenzial hat, Schiffe manövrierunfähig zu machen und so für eine Übernahme vorzubereiten.<br/>
Die bisher höchste Form einer EMP-Waffe ist das Ionengeschütz. Es schleudert eine Welle von Ionen (elektrisch geladener Teilchen) auf das Ziel, welches die Schilde destabilisiert und alle Elektronik inklusive der lebenserhaltenden Systeme unbrauchbar macht.<br/>
Die Ionentechnik wird auch auf Kreuzern und Zerstörern eingesetzt. Allerdings ist der Energieaufwand dieser Waffen sehr hoch und in einem Gefecht kommt es häufig darauf an, das Ziel zu zerstören und nicht nur zu paralysieren. Verteidigungsanlagen deaktivieren sich, sobald sie zu stark beschädigt sind.";
$LOCA["de"]["LONG_406"] = "Die Lasertechnik war nahezu perfekt, und auch die Ionentechnik war schon so weit, dass es als unmöglich galt, die bestehenden Systeme auch nur ein Stück effektiver zu machen - als man auf die Idee kam, beide Systeme miteinander zu kombinieren! Wie auch bei der Kernfusion erhitzen Laser Teilchen (meistens Deuterium) auf extrem hohe Temperaturen. Die Ionentechnik trägt ihren Teil in Form von elektrischer Aufladung, Stabilisierungsfeldern und Beschleunigern bei. Die abzufeuernde Ladung wird erhitzt, unter Druck gesetzt, ionisiert und mit einem imposanten Feuerstrahl ins All hinausgejagt.<br/>
Die Crew des Zielschiffs wird an diesem Lichtspiel allerdings nur kurz Gefallen finden, bevor der tödliche Strahl alles zerreißt.<br/>
Der Plasmawerfer gilt als gefürchtete Waffe, diese Technik hat allerdings auch ihren Preis.<br/>
Verteidigungsanlagen deaktivieren sich, sobald sie zu stark beschädigt sind.";
$LOCA["de"]["LONG_407"] = "Lange bevor die Schildgeneratoren klein genug waren, um auf Schiffen Einsatz zu finden, gab es bereits erste Versuche mit riesigen Schildkuppeln auf der Oberfläche von Planeten. Diese umfassten den gesamten Orbit mit einem Kraftfeld, welches ungeheure Energiemengen absorbieren kann. Kleinere Angriffsflotten scheitern auch heute noch an diesen Schildkuppeln. Mit zunehmender technologischer Entwicklung können diese Schilde noch verstärkt oder zu einer großen Schildkuppel ausgebaut werden. Pro Planet ist nur eine solche Vorrichtung möglich.";
$LOCA["de"]["LONG_408"] = "Die Weiterentwicklung der kleinen Schildkuppel. Sie basiert auf derselben Technologie, kann aber wesentlich mehr Energie einsetzen, um feindliche Angriffe abzuwehren.";
$LOCA["de"]["LONG_502"] = "Nur eine Abfangrakete kann deinen Planeten und Mond vor einer ankommenden Interplanetarrakete schützen. Eine Abfangrakete startet vollkommen automatisch, wenn eine Interplanetarrakete kurz vor dem Einschlag steht, und zerstört diese.";
$LOCA["de"]["LONG_503"] = "Interplanetarraketen zerstören die gegnerische Verteidigung, können allerdings durch Abfangraketen zerstört werden. Von Interplanetarraketen zerstörte Verteidigungsanlagen bauen sich nicht wieder auf.";

?>